export const archiveFileLimit = 50 * 1024 * 1024;
const archiveRoots = {notes:'notes-root',research:'research-root'};
const archiveLabels = {notes:'学习笔记',research:'研究进展'};
const archiveJson = (value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
class ArchiveProblem extends Error {constructor(message,status=400){super(message);this.status=status;}}
function archiveName(value){if(typeof value!=='string'||value.length<1||value.length>240||!value.trim()||value==='.'||value==='..'||/[\\/\x00-\x1f\x7f]/.test(value))throw new ArchiveProblem('目录或文件名无效：请使用 1–240 个字符，不包含斜杠和控制字符。');return value;}
function archiveDescription(value){if(typeof value!=='string'||value.length>20000)throw new ArchiveProblem('简介最多可写 20000 个字符。');return value;}
async function archiveBody(request){if(!request.headers.get('content-type')?.startsWith('application/json'))throw new ArchiveProblem('请使用 JSON 格式。',415);const text=await request.text();if(text.length>30000)throw new ArchiveProblem('内容过长。',413);try{return JSON.parse(text);}catch{throw new ArchiveProblem('无法识别提交内容。');}}
async function archiveFind(db,id){const entry=await db.prepare('SELECT * FROM archive_entries WHERE id=?').bind(id).first();if(!entry)throw new ArchiveProblem('这个目录或文件不存在，请返回上一级重试。',404);return entry;}
async function archiveFolder(db,id){const entry=await archiveFind(db,id);if(entry.kind!=='folder')throw new ArchiveProblem('请选择一个目录。');return entry;}
function archiveMutation(request,editor){if(!editor)throw new ArchiveProblem('只有网站所有者可以创建目录和上传文件。',403);if(request.headers.get('origin')!==new URL(request.url).origin)throw new ArchiveProblem('请求来源不匹配。',403);}
function archiveUnique(error){return /UNIQUE constraint failed|unique constraint/i.test(String(error?.message));}
async function archiveSeed(db){const time=new Date().toISOString();const initial=[['notes-root','','notes','学习笔记'],['research-root','','research','研究进展'],['notes-space','notes-root','notes','空间物理'],['notes-computer','notes-root','notes','计算机科学'],['notes-economics','notes-root','notes','经济学']];await db.batch(initial.map(([id,parent,section,name])=>db.prepare('INSERT OR IGNORE INTO archive_entries (id,parent_id,section,kind,name,description,size,revision,created_at) VALUES (?,?,?,\'folder\',?,\'\',0,0,?)').bind(id,parent,section,name,time)));}
async function archiveList(db,folderId,editor){const folder=await archiveFolder(db,folderId);const children=await db.prepare('SELECT e.id,e.parent_id,e.section,e.kind,e.name,e.description,e.size,e.revision,e.created_at,(SELECT count(*) FROM archive_entries c WHERE c.parent_id=e.id) AS child_count FROM archive_entries e WHERE e.parent_id=? ORDER BY e.kind DESC,e.name COLLATE NOCASE,e.id').bind(folderId).all();const trail=await db.prepare('WITH RECURSIVE ancestors AS (SELECT id,parent_id,name,0 AS depth FROM archive_entries WHERE id=? UNION ALL SELECT e.id,e.parent_id,e.name,a.depth+1 FROM archive_entries e JOIN ancestors a ON e.id=a.parent_id) SELECT id,name FROM ancestors ORDER BY depth DESC').bind(folderId).all();return {initialized:true,canEdit:editor,folder,entries:children.results,breadcrumbs:trail.results,maxFileBytes:archiveFileLimit};}
export async function archiveRoute(request,env,editor){const url=new URL(request.url);const pathname=url.pathname;if(!pathname.startsWith('/api/archive'))return null;
try {
if(!env.DB)throw new ArchiveProblem('目录暂时不可用，请稍后重试。',503);const db=env.DB;
if(pathname==='/api/archive'&&request.method==='GET'){const section=url.searchParams.get('section')||'notes';if(!Object.hasOwn(archiveRoots,section))throw new ArchiveProblem('请选择研究进展或学习笔记。');const root=await db.prepare('SELECT id FROM archive_entries WHERE id=?').bind(archiveRoots[section]).first();if(!root)return archiveJson({initialized:false,canEdit:editor,maxFileBytes:archiveFileLimit});const id=url.searchParams.get('folder')||archiveRoots[section];const data=await archiveList(db,id,editor);if(data.folder.section!==section)throw new ArchiveProblem('目录不属于当前栏目。');return archiveJson(data);}
if(pathname==='/api/archive/init'&&request.method==='POST'){archiveMutation(request,editor);await archiveSeed(db);return archiveJson({initialized:true});}
if(pathname==='/api/archive/folders'&&request.method==='POST'){archiveMutation(request,editor);const body=await archiveBody(request);const parent=await archiveFolder(db,body.parentId);const name=archiveName(body.name);const description=archiveDescription(body.description??'');const existing=await db.prepare('SELECT * FROM archive_entries WHERE parent_id=? AND name=?').bind(parent.id,name).first();if(existing){if(body.reuseExisting===true&&existing.kind==='folder')return archiveJson({entry:existing,reused:true});throw new ArchiveProblem('这个位置已有同名目录或文件，请换一个名称。',409);}
const id=crypto.randomUUID();try{await db.prepare('INSERT INTO archive_entries (id,parent_id,section,kind,name,description,size,revision,created_at) VALUES (?,?,?,\'folder\',?,?,0,0,?)').bind(id,parent.id,parent.section,name,description,new Date().toISOString()).run();}catch(error){if(!archiveUnique(error))throw error;const retry=await db.prepare('SELECT * FROM archive_entries WHERE parent_id=? AND name=?').bind(parent.id,name).first();if(body.reuseExisting===true&&retry?.kind==='folder')return archiveJson({entry:retry,reused:true});throw new ArchiveProblem('这个位置已有同名目录或文件，请换一个名称。',409);}return archiveJson({entry:await archiveFind(db,id)},201);}
const folderMatch=pathname.match(/^\/api\/archive\/folders\/([^/]+)$/);
if(folderMatch&&request.method==='PATCH'){archiveMutation(request,editor);const folder=await archiveFolder(db,folderMatch[1]);const body=await archiveBody(request);const name=archiveName(body.name),description=archiveDescription(body.description);if(!Number.isSafeInteger(body.revision)||body.revision<0)throw new ArchiveProblem('编辑版本无效，请刷新重试。');try{const result=await db.prepare('UPDATE archive_entries SET name=?,description=?,revision=revision+1 WHERE id=? AND revision=?').bind(name,description,folder.id,body.revision).run();if(result.meta.changes!==1)throw new ArchiveProblem('其他页面已修改此目录，请复制当前输入后刷新重试。',409);}catch(error){if(archiveUnique(error))throw new ArchiveProblem('这个位置已有同名目录或文件，请换一个名称。',409);throw error;}return archiveJson({entry:await archiveFind(db,folder.id)});}
if(pathname==='/api/archive/upload'&&request.method==='PUT'){archiveMutation(request,editor);if(!env.BUCKET)throw new ArchiveProblem('上传暂时不可用，请稍后重试。',503);const folder=await archiveFolder(db,url.searchParams.get('folder'));const name=archiveName(url.searchParams.get('name'));const id=url.searchParams.get('id');if(!/^[a-f0-9-]{36}$/.test(id??''))throw new ArchiveProblem('上传标识无效。');const size=Number(url.searchParams.get('size'));if(!Number.isSafeInteger(size)||size<0||size>archiveFileLimit)throw new ArchiveProblem('单个文件最大支持 50 MiB，请减小文件后重试。',413);
const duplicate=await db.prepare('SELECT * FROM archive_entries WHERE parent_id=? AND name=?').bind(folder.id,name).first();if(duplicate){if(duplicate.id===id&&duplicate.kind==='file'&&duplicate.size===size)return archiveJson({entry:duplicate,alreadySaved:true});throw new ArchiveProblem('已存在同名目录或文件，原文件保留，请改名后上传。',409);}
const sameId=await db.prepare('SELECT id FROM archive_entries WHERE id=?').bind(id).first();if(sameId)throw new ArchiveProblem('上传标识已使用，请重新选择文件。',409);
const declared=request.headers.get('content-length');if(declared!==null&&Number(declared)!==size)throw new ArchiveProblem('文件大小不匹配，请重新选择文件。');
// Stream into R2. A fresh object key isolates simultaneous attempts and never overwrites originals.
const key='archive/'+id+'/'+crypto.randomUUID();let stored=false;
try{const object=await env.BUCKET.put(key,size===0?new Uint8Array():request.body,{httpMetadata:{contentType:'application/octet-stream'}});stored=true;if(object.size!==size)throw new ArchiveProblem('文件未完整上传，请重试。');await db.prepare('INSERT INTO archive_entries (id,parent_id,section,kind,name,description,object_key,size,revision,created_at) VALUES (?,?,?,\'file\',?,\'\',?,?,0,?)').bind(id,folder.id,folder.section,name,key,size,new Date().toISOString()).run();stored=false;return archiveJson({entry:await archiveFind(db,id)},201);}catch(error){if(stored)try{await env.BUCKET.delete(key);}catch(cleanup){console.error('Unlinked archive object cleanup failed',cleanup);}if(archiveUnique(error)){const latest=await db.prepare('SELECT * FROM archive_entries WHERE id=?').bind(id).first();if(latest?.parent_id===folder.id&&latest.name===name&&latest.size===size)return archiveJson({entry:latest,alreadySaved:true});throw new ArchiveProblem('已存在同名文件，原文件保留，请改名后上传。',409);}throw error;}}
const fileMatch=pathname.match(/^\/api\/archive\/files\/([^/]+)$/);
if(fileMatch&&['GET','HEAD'].includes(request.method)){const file=await archiveFind(db,fileMatch[1]);if(file.kind!=='file')throw new ArchiveProblem('请选择一个文件。');if(!env.BUCKET)throw new ArchiveProblem('文件暂时不可用。',503);const object=await env.BUCKET.get(file.object_key);if(!object)throw new ArchiveProblem('文件暂时无法读取，请稍后重试。',503);const filename=encodeURIComponent(file.name).replace(/[!'()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase());return new Response(request.method==='HEAD'?null:object.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+filename,'Content-Length':String(object.size),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
return archiveJson({error:'不支持此操作。'},405);
}catch(error){if(error instanceof ArchiveProblem)return archiveJson({error:error.message},error.status);console.error('Archive operation failed',error);return archiveJson({error:'暂时无法完成此操作。已保存的内容不会丢失，请稍后重试。'},503);}
}
