import test from 'node:test';
import assert from 'node:assert/strict';
import {readPreviewBytes,parseCSV,parseFITSHeader,fitsImageLayout,parseFITSImage,notebookCells} from '../src/file-preview/parsers.mjs';
const card=value=>value.padEnd(80,' ');
function fitsFixture(bitpix,values,{width=2,height=2,extra=[]}={}){const text=[card('SIMPLE  =                    T'),card(`BITPIX  = ${bitpix}`),card('NAXIS   =                    2'),card(`NAXIS1  = ${width}`),card(`NAXIS2  = ${height}`),...extra.map(card),card('END')].join('').padEnd(2880,' '),bytes=new Uint8Array(2880+values.length*Math.abs(bitpix)/8);bytes.set(new TextEncoder().encode(text));const data=new DataView(bytes.buffer,2880);for(const [index,value]of values.entries()){const offset=index*Math.abs(bitpix)/8;if(bitpix===16)data.setInt16(offset,value,false);else if(bitpix===-32)data.setFloat32(offset,value,false);else if(bitpix===64)data.setBigInt64(offset,value,false);}return bytes;}

test('FITS 2D reads big-endian scaled pixels and preserves blank values',()=>{const bytes=fitsFixture(16,[0,10,-32768,20],{extra:['BSCALE  = 2.0D+00','BZERO   = 1.0','BLANK   = -32768',"EXPTIME = 0.05 / seconds"]}),header=parseFITSHeader(bytes),image=parseFITSImage(bytes,header);assert.equal(header.dataOffset,2880);assert.equal(header.exposure,'0.05');assert.deepEqual(Array.from(image.data),[1,21,NaN,41]);assert.equal(image.min,1);assert.equal(image.max,41);assert.equal(image.finite,3);assert.equal(image.precisionWarning,false);});
test('FITS floating-point NaN and 64-bit integer approximation are explicit',()=>{const floating=parseFITSImage(fitsFixture(-32,[1.5,NaN,-2,Infinity]));assert.equal(floating.finite,2);assert.equal(floating.min,-2);assert.equal(floating.max,1.5);const integers=parseFITSImage(fitsFixture(64,[1n,2n,3n,4n]));assert.equal(integers.precisionWarning,true);assert.deepEqual(Array.from(integers.data),[1,2,3,4]);});
test('FITS preview rejects huge images, table HDUs, random groups and incomplete payloads',()=>{const bytes=fitsFixture(16,[1,2,3,4]),header=parseFITSHeader(bytes);assert.equal(fitsImageLayout({...header,values:{...header.values,NAXIS1:'100000',NAXIS2:'100000'}}),null);assert.equal(fitsImageLayout({...header,values:{...header.values,XTENSION:'BINTABLE'}}),null);assert.equal(fitsImageLayout({...header,values:{...header.values,GROUPS:'T'}}),null);assert.throws(()=>parseFITSImage(bytes.subarray(0,2881),header),/incomplete/);});
test('range reads validate offsets, cancel ignored continuation ranges and know complete length',async()=>{let cancelled=false;const ignored=new ReadableStream({pull(controller){controller.enqueue(new Uint8Array(20));},cancel(){cancelled=true;}});await assert.rejects(()=>readPreviewBytes('https://example.org/file',{start:10,limit:5,fetcher:async()=>new Response(ignored)}),/additional preview ranges/);assert.equal(cancelled,true);let header;const result=await readPreviewBytes('https://example.org/file',{start:10,limit:5,fetcher:async(_url,options)=>{header=options.headers.Range;return new Response(new Uint8Array([1,2,3,4,5]),{status:206,headers:{'content-range':'bytes 10-14/15'}});}});assert.equal(header,'bytes=10-15');assert.equal(result.truncated,false);assert.equal(result.total,15);assert.equal(result.bytes.length,5);});
test('CSV preview excludes incomplete range-cut rows and caps 500 data rows',()=>{assert.deepEqual(parseCSV('a,b\n1,2\n3,',{includePartial:false}),[['a','b'],['1','2']]);assert.deepEqual(parseCSV('a,b\n1,"partial',{includePartial:true}),[['a','b']]);assert.equal(parseCSV('a\n'+Array.from({length:1000},(_,index)=>index).join('\n'),{rows:501}).length,501);});
test('static notebook retains execution counts but never interprets saved HTML',()=>{const cell=notebookCells(JSON.stringify({nbformat:4,cells:[{cell_type:'code',execution_count:8,source:['print(8)'],outputs:[{data:{'text/html':'<script>throw 1</script>','text/plain':'8'}}]}]}))[0];assert.equal(cell.executionCount,8);assert.equal(cell.source,'print(8)');assert.equal(cell.outputs[0].data['text/html'],'<script>throw 1</script>');});
