import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { assertAllowedPath, validateChangeSet, OWNER_LIMITS, utf8Bytes, encodeBase64, validateAsset, validateMetadata } from '../src/lib/owner/policy.mjs';
import { readOwnerModel, parseContentFile, serializeContentDocument, convertMdxToMarkdown, createEntryChanges, updateEntryChanges, deleteEntryChanges, createDocumentChanges, updateDocumentChanges, deleteDocumentChanges, createLogChanges, updateDataChanges, uploadAssetChanges, importFolderChanges, analyzeUploadFiles, applyDraftToSnapshot, mergeDraftChanges, normalizeTags, moveAssetChanges, deleteAssetChanges } from '../src/lib/owner/model.mjs';
import { createOwnerMiddleware, localOwnerSnapshot, applyLocalOwnerPublish } from '../scripts/owner-local-plugin.mjs';

const data={title:'Solar alignment',description:'An actual study plan.',date:'2026-10-02',updated:'2026-10-03',tags:['Solar Physics'],status:'Planning',featured:false,demo:false};
const profile={name:'Z-hang',displayName:'Z-hang',bio:'A student.',university:'Peking University',degree:'Space Physics',secondDegree:'Computer Science',lastUpdated:'2026-10-03',currently:[],education:[],timeline:[],links:[]};
function file(p,content,sha='original'){return {path:p,content,encoding:'utf8',sha,size:utf8Bytes(content).length};}
function snapshot(){return {head:'start',files:[file('hub/src/data/profile.yaml','name: Z-hang\ndisplayName: Z-hang\nbio: A student.\nuniversity: Peking University\ndegree: Space Physics\nsecondDegree: Computer Science\nlastUpdated: 2026-10-03\n'),file('hub/src/data/navigation.yaml','- label: Home\n  href: /\n'),file('hub/src/content/research/solar-alignment/index.md',serializeContentDocument({metadata:data,body:'## Question\n\nPreserve originals.\n\n## Method\n\nCheck residuals.\n'}))]};}

test('existing profile and content are read without entering metadata again',()=>{const model=readOwnerModel(snapshot());assert.equal(model.profile.name,'Z-hang');assert.equal(model.entries.research[0].slug,'solar-alignment');assert.equal(model.entries.research[0].sections.length,2);assert.equal(model.homepage.sections[0].id,'hero');});
test('creating collections generates safe Markdown and rejects duplicate URL',()=>{for(const kind of ['research','notes','projects']){const changes=createEntryChanges(snapshot(),{kind,metadata:{...data,title:'New Material'},body:'## Overview\n\nStudy $x^2$.'});assert.match(changes[0].path,new RegExp(`/content/${kind}/new-material/index.md$`));validateChangeSet(changes,{snapshotFiles:snapshot().files});}assert.throws(()=>createEntryChanges(snapshot(),{kind:'research',slug:'solar-alignment',metadata:data}),/already exists/);});
test('title changes preserve the slug, tags normalize spelling variants',()=>{const changes=updateEntryChanges(snapshot(),{kind:'research',slug:'solar-alignment',metadata:{title:'A new title',tags:['Solar Physics','solar-physics','Solar Physics','FITS']}});assert.equal(changes[0].path,'hub/src/content/research/solar-alignment/index.md');assert.deepEqual(parseContentFile({...changes[0],sha:'x'}).metadata.tags,['Solar Physics','FITS']);assert.deepEqual(normalizeTags(' Plasma Physics,plasma-physics,  IDL'),['Plasma Physics','IDL']);});
test('section reorder produces a real Markdown reorder',()=>{const original=readOwnerModel(snapshot()).entries.research[0];const changes=updateEntryChanges(snapshot(),{kind:'research',slug:original.slug,sections:[...original.sections].reverse()});assert.ok(changes[0].content.indexOf('## Method')<changes[0].content.indexOf('## Question'));});
test('deletion requires title confirmation and includes assets and project logs',()=>{const source=snapshot();source.files.push(file('hub/src/content/logs/solar-alignment/update.md',serializeContentDocument({metadata:{title:'Update',project:'solar-alignment',date:'2026-10-03'},body:'Checked.'})),file('hub/public/uploads/research/solar-alignment/source.txt','Original source'));assert.throws(()=>deleteEntryChanges(source,{kind:'research',slug:'solar-alignment',confirmation:'wrong'}),/exact article title/);const changes=deleteEntryChanges(source,{kind:'research',slug:'solar-alignment',confirmation:data.title});assert.equal(changes.length,3);assert.ok(changes.every(change=>change.action==='delete'));validateChangeSet(changes,{snapshotFiles:source.files});});
test('research updates validate their existing parent and dates',()=>{const changes=createLogChanges(snapshot(),{project:'solar-alignment',metadata:{title:'Improved checks',date:'2026-10-03'},body:'A dated update.'});validateChangeSet(changes,{snapshotFiles:snapshot().files});assert.throws(()=>createLogChanges(snapshot(),{project:'missing',metadata:{title:'Update'}}),/existing research/);assert.throws(()=>createLogChanges(snapshot(),{project:'solar-alignment',metadata:{title:'Update',date:'2026-02-30'}}),/calendar date/);});
test('known MDX components convert preserving equations and code byte for byte',()=>{const body="import Figure from '../../../components/Figure.astro';\nimport Callout from '../../../components/Callout.astro';\n\n## Study\n\n<Callout title=\"Units\">\nCheck units.\n</Callout>\n\n<Figure src=\"/images/solar-study.svg\" alt=\"Schematic\" number={1} caption=\"Illustration\" />\n\n$$\n\\frac{x}{y}=1\n$$\n\n```python\nresult = {'price': '$&'}\n```\n";const converted=convertMdxToMarkdown(body);assert.match(converted,/> \*\*Units\*\*/);assert.match(converted,/!\[Schematic\]\(\/images\/solar-study.svg\)/);assert.ok(converted.includes('$$\n\\frac{x}{y}=1\n$$'));assert.ok(converted.includes("```python\nresult = {'price': '$&'}\n```"));assert.doesNotMatch(converted,/import Figure|<Callout/);});
test('MDX metadata changes retain original body; body edit creates Markdown and original download',()=>{const source=snapshot();const p='hub/src/content/research/solar-alignment/index.mdx';source.files[2]=file(p,serializeContentDocument({metadata:data,body:"import Callout from '../../../components/Callout.astro';\n\n## Overview\n\n<Callout title=\"Original\">\nCheck assumptions.\n</Callout>\n"}));const metadataOnly=updateEntryChanges(source,{kind:'research',slug:'solar-alignment',metadata:{featured:true}});assert.equal(metadataOnly[0].path,p);assert.equal(parseContentFile(metadataOnly[0]).body,parseContentFile(source.files[2]).body);validateChangeSet(metadataOnly,{snapshotFiles:source.files});const changes=updateEntryChanges(source,{kind:'research',slug:'solar-alignment',body:parseContentFile(source.files[2]).editBody+'\nA new paragraph.\n'});assert.equal(changes.length,3);assert.ok(changes.some(c=>c.action==='delete'&&c.path===p));assert.ok(changes.some(c=>c.path.endsWith('owner-originals/research/solar-alignment/index.mdx')));validateChangeSet(changes,{snapshotFiles:source.files});});
test('raw executable MDX and Markdown HTML cannot enter code execution paths',()=>{const source=snapshot(),content=serializeContentDocument({metadata:data,body:'export const p = fetch("https://attacker");\n\n{process.env.SECRET}'});assert.throws(()=>validateChangeSet([{path:'hub/src/content/research/new-study/index.mdx',action:'upsert',content,encoding:'utf8',expectedSha:null}],{snapshotFiles:source.files}),/MDX/);assert.throws(()=>createEntryChanges(source,{kind:'research',slug:'new-study',metadata:data,body:'<script>alert(1)</script>'}),/Raw HTML/);assert.throws(()=>createEntryChanges(source,{kind:'research',slug:'new-study',metadata:data,body:'[click](javascript:alert)' }),/Unsafe link/);assert.throws(()=>convertMdxToMarkdown('<Unknown dangerous={run()} />'),/cannot be safely converted/);});
test('path allowlist rejects source code, config, traversal, secrets and double encoding',()=>{for(const p of ['hub/../package.json','hub/.github/workflows/deploy.yml','hub/src/components/Card.astro','hub/src/data/secrets.yaml','hub/public/uploads/files/../../x.txt','hub/public/uploads/files/%2e%2e/x.txt','hub/public/uploads/files/x.svg','hub/public/uploads/files/x.js','hub/public/uploads/files/CON.txt','hub/public/uploads/files/secret.key'])assert.throws(()=>assertAllowedPath(p),undefined,p);assert.equal(assertAllowedPath('hub/public/uploads/notes/course-a/图像/图1.png'),'hub/public/uploads/notes/course-a/图像/图1.png');});
test('publish revisions and case conflicts prevent silent overwrite',()=>{const source=snapshot(),changes=updateDataChanges(source,{profile});changes[0].expectedSha='stale';assert.throws(()=>validateChangeSet(changes,{snapshotFiles:source.files}),error=>error.statusCode===409);assert.throws(()=>validateChangeSet([{path:'hub/public/uploads/files/A.txt',action:'upsert',content:'a',encoding:'utf8',expectedSha:null},{path:'hub/public/uploads/files/a.txt',action:'upsert',content:'b',encoding:'utf8',expectedSha:null}],{snapshotFiles:[]}),/case-colliding/);});
test('asset signatures, declared MIME, UTF-8 and sizes are validated',()=>{assert.throws(()=>validateAsset('hub/public/uploads/files/paper.pdf',utf8Bytes('not a PDF'),'application/pdf'),/do not match/);assert.throws(()=>validateAsset('hub/public/uploads/images/plot.png',new Uint8Array([137,80,78,71,13,10,26,10]),'text/html'),/MIME/);assert.throws(()=>validateAsset('hub/public/uploads/files/source.txt',new Uint8Array([255])),/UTF-8/);assert.throws(()=>validateAsset('hub/public/uploads/files/data.csv',new Uint8Array(OWNER_LIMITS.fileBytes+1)),error=>error.statusCode===413);const fits=utf8Bytes('SIMPLE  ='.padEnd(2880,' '));assert.equal(validateAsset('hub/public/uploads/files/test.fits',fits).size,2880);assert.equal(validateAsset('hub/public/uploads/files/notes.zip',new Uint8Array([80,75,5,6])).extension,'zip');});
test('folder uploads preserve hierarchy, original bytes and safe reading copies',()=>{const source=snapshot(),uploads=[{path:'README.md',content:'# Overview\n\n![Figure](figures/图1.png)\n\n[Lecture](Lecture01.md)',encoding:'utf8',mime:'text/markdown'},{path:'Lecture01.md',content:'# Lecture\n\n$$\\nabla \\cdot \\mathbf B=0$$\n\n<iframe src="https://example.com"></iframe>',encoding:'utf8',mime:'text/markdown'},{path:'figures/图1.png',content:encodeBase64(new Uint8Array([137,80,78,71,13,10,26,10])),encoding:'base64',mime:'image/png'}];const analysis=analyzeUploadFiles(uploads);assert.equal(analysis.recognized.readme,'README.md');const changes=uploadAssetChanges(source,{kind:'research',slug:'solar-alignment',files:uploads,useReadme:true});validateChangeSet(changes,{snapshotFiles:source.files});const original=changes.find(c=>c.path.endsWith('/Lecture01.md')&&c.path.startsWith('hub/public/'));assert.equal(original.content,uploads[1].content);const reading=changes.find(c=>c.path.includes('/files/Lecture01.md'));assert.match(reading.content,/&lt;iframe/);const index=changes.find(c=>c.path.endsWith('/index.md'));assert.match(index.content,/\/uploads\/research\/solar-alignment\/figures\/%E5%9B%BE1.png/);assert.match(index.content,/\/research\/solar-alignment\/files\/Lecture01\//);assert.equal(parseContentFile(index).metadata.documents.length,2);});
test('recognition never replaces article overview without explicit confirmation',()=>{const source=snapshot(),changes=uploadAssetChanges(source,{kind:'research',slug:'solar-alignment',files:[{path:'README.md',encoding:'utf8',content:'Replace everything'}]});assert.equal(parseContentFile(changes.find(c=>c.path.endsWith('/index.md'))).body,parseContentFile(source.files[2]).body);});
test('folder import creates a course and all reading pages in one draft while preserving original materials',()=>{
  const source=snapshot(),baseline=structuredClone(source),uploads=[
    {path:'README.md',encoding:'utf8',content:'# Course materials\n\n[Lecture](Lectures/01.md)\n\n[Handout](HW01.pdf)'},
    {path:'Lectures/01.md',encoding:'utf8',content:'# First lecture\n\n$$\\nabla\\cdot\\mathbf B=0$$\n\n![Figure](../Figures/图1.png)\n\n<iframe src="https://example.com"></iframe>'},
    {path:'HW01.pdf',encoding:'base64',content:encodeBase64(utf8Bytes('%PDF-original')),mime:'application/pdf'},
    {path:'Figures/图1.png',encoding:'base64',content:encodeBase64(new Uint8Array([137,80,78,71,13,10,26,10])),mime:'image/png'},
  ];
  const changes=importFolderChanges(source,{kind:'notes',slug:'confirmed-course',metadata:{...data,title:'Confirmed course',course:'Confirmed course',semester:'2026 Fall',category:'Space Physics'},files:uploads,useReadme:true});
  validateChangeSet(changes,{snapshotFiles:source.files});assert.deepEqual(source,baseline);
  assert.equal(new Set(changes.map(change=>change.path)).size,changes.length);assert(changes.every(change=>change.expectedSha===null));
  const parent=changes.filter(change=>change.path==='hub/src/content/notes/confirmed-course/index.md');assert.equal(parent.length,1);
  const entry=parseContentFile(parent[0]);assert.equal(entry.metadata.semester,'2026 Fall');assert.equal(entry.metadata.category,'Space Physics');assert.equal(entry.metadata.demo,false);
  assert.match(entry.body,/\/notes\/confirmed-course\/files\/Lectures\/01\//);assert.equal(entry.metadata.documents.length,2);
  const archive=changes.find(change=>change.path==='hub/public/uploads/notes/confirmed-course/Lectures/01.md');assert.equal(archive.content,uploads[1].content);
  const reading=changes.find(change=>change.path==='hub/src/content/notes/confirmed-course/files/Lectures/01.md');assert.match(reading.content,/&lt;iframe/);assert.match(reading.content,/\\nabla\\cdot\\mathbf B=0/);assert.match(reading.content,/\/uploads\/notes\/confirmed-course\/Figures\/%E5%9B%BE1.png/);
  assert.equal(changes.find(change=>change.path==='hub/public/uploads/notes/confirmed-course/HW01.pdf').content,uploads[2].content);
});
test('new research folder recognition applies only the owner-confirmed overview, cover and paper choices',()=>{
  const source=snapshot(),files=[{path:'README.md',encoding:'utf8',content:'# Imported overview\n\nKeep the actual material.'},{path:'cover.png',encoding:'base64',content:encodeBase64(new Uint8Array([137,80,78,71,13,10,26,10])),mime:'image/png'},{path:'paper.pdf',encoding:'utf8',content:'%PDF-original',mime:'application/pdf'}];
  const options={kind:'research',slug:'new-folder',metadata:{...data,title:'Actual folder'},files};
  const unconfirmed=parseContentFile(importFolderChanges(source,options).find(change=>change.path.endsWith('/index.md')));assert.equal(unconfirmed.body.trim(),'');assert.equal(unconfirmed.metadata.cover,undefined);assert.equal(unconfirmed.metadata.paper,undefined);
  const confirmed=parseContentFile(importFolderChanges(source,{...options,useReadme:true,useCover:true,usePaper:true}).find(change=>change.path.endsWith('/index.md')));assert.match(confirmed.body,/Keep the actual material/);assert.equal(confirmed.metadata.cover,'/uploads/research/new-folder/cover.png');assert.equal(confirmed.metadata.paper,'/uploads/research/new-folder/paper.pdf');
});
test('new folder import refuses existing parent URLs, unsafe files and invalid course metadata without changing the baseline',()=>{
  const source=snapshot(),baseline=structuredClone(source),options={kind:'research',slug:'solar-alignment',metadata:data,files:[{path:'README.md',encoding:'utf8',content:'# Overview'}]};
  assert.throws(()=>importFolderChanges(source,options),/already exists/);
  assert.throws(()=>importFolderChanges(source,{...options,slug:'new-folder',files:[{path:'../escape.txt',encoding:'utf8',content:'Forbidden'}]}),/traversal|relative path/);
  assert.throws(()=>importFolderChanges(source,{...options,kind:'notes',slug:'new-course',metadata:{...data,semester:'2026 Fall',category:'Invalid category'}}),/category/);
  assert.deepEqual(source,baseline);
});
test('folder import supports batches beyond the former 250 changed-file cap',()=>{
  const source=snapshot(),options={kind:'research',slug:'too-many-readings',metadata:data};
  const files=Array.from({length:125},(_,index)=>({path:`Lecture${index}.md`,encoding:'utf8',content:'# Lecture\n\nOriginal material.'}));
  assert.ok(importFolderChanges(source,{...options,files}).length>250);
  assert.equal(source.files.length,3);
});
test('general uploads and asset moves keep sources and update approved references',()=>{const source=snapshot();const upload=uploadAssetChanges(source,{kind:'general',target:'documents',files:[{path:'handout.txt',encoding:'utf8',content:'Original'}]});validateChangeSet(upload,{snapshotFiles:source.files});const draft=applyDraftToSnapshot(source,upload);draft.files.find(f=>f.path==='hub/public/uploads/documents/handout.txt').sha='asset';const moved=moveAssetChanges(draft,{from:'hub/public/uploads/documents/handout.txt',to:'hub/public/uploads/files/renamed.txt',confirmation:'handout.txt'});assert.equal(moved.length,2);assert.equal(moved[0].content,'Original');assert.throws(()=>deleteAssetChanges(draft,{path:'hub/public/uploads/documents/handout.txt',confirmation:'wrong'}),/Confirm/);});
test('draft merging maintains original SHA and cancels unpublished additions',()=>{const source=snapshot(),first=createEntryChanges(source,{kind:'projects',metadata:{...data,title:'New project'}}),draft=applyDraftToSnapshot(source,first),edit=updateEntryChanges(draft,{kind:'projects',slug:'new-project',metadata:{title:'Renamed'}});const merged=mergeDraftChanges(source,first,edit);assert.equal(merged.length,1);assert.equal(merged[0].expectedSha,null);const deletions=deleteEntryChanges(applyDraftToSnapshot(source,merged),{kind:'projects',slug:'new-project',confirmation:'Renamed'});assert.deepEqual(mergeDraftChanges(source,merged,deletions),[]);});
test('homepage, navigation and structured profile forms validate before draft save',()=>{const source=snapshot();assert.throws(()=>updateDataChanges(source,{navigation:[{label:'Unsafe',href:'javascript:run()'}]}),/Unsafe/);assert.throws(()=>updateDataChanges(source,{profile:{...profile,timeline:[{date:'2026'}]}}),/timeline.title/);assert.throws(()=>updateDataChanges(source,{homepage:{sections:[{id:'hero',order:0,visible:true},{id:'hero',order:1,visible:true}]}}),/unique/);});
test('camel case tags reuse existing spelling without merging C, C++ and C#',()=>{const changes=createEntryChanges(snapshot(),{kind:'research',slug:'new-tags',metadata:{...data,tags:['SolarPhysics','solar-physics','C','C++','C#']}});assert.deepEqual(parseContentFile(changes[0]).metadata.tags,['Solar Physics','C','C++','C#']);});
test('schema-invalid metadata is rejected before a commit can trigger a failed build',()=>{for(const metadata of [{...data,cover:''},{...data,github:'relative/repo'},{...data,references:[{title:'Reference',authors:'One author'}]},{...data,references:[{title:'Reference',year:2026.5}]},{...data,references:[{title:'Reference',doi:42}]}])assert.throws(()=>validateMetadata(metadata,{kind:'research'}));assert.throws(()=>validateMetadata({...data,course:'Physics',semester:'2026 Fall',category:'Physics',year:2026.5},{kind:'notes'}),/Course year/);});
test('forms can clear optional metadata links and normalize reference authors',()=>{const source=snapshot();const original=parseContentFile(source.files[2]);original.metadata.cover='/images/original.png';source.files[2].content=serializeContentDocument({metadata:original.metadata,body:original.body});const changes=updateEntryChanges(source,{kind:'research',slug:'solar-alignment',metadata:{cover:'',references:[{title:'Reference',authors:'First Author, Second Author',url:''}]}});const metadata=parseContentFile(changes[0]).metadata;assert.equal(metadata.cover,undefined);assert.deepEqual(metadata.references[0].authors,['First Author','Second Author']);assert.equal(metadata.references[0].url,undefined);validateChangeSet(changes,{snapshotFiles:source.files});const links=updateDataChanges(source,{profile:{...profile,links:[{label:'GitHub',url:'https://github.com/Z-hang729'}]}});validateChangeSet(links,{snapshotFiles:source.files});});
test('course reading note CRUD updates parent listing while preserving original archive',()=>{const source=snapshot(),changes=createDocumentChanges(source,{kind:'research',slug:'solar-alignment',path:'Lectures/01.md',metadata:{title:'First lecture'},body:'## Formula\n\n$E=mc^2$'});validateChangeSet(changes,{snapshotFiles:source.files});const draft=applyDraftToSnapshot(source,changes),notePath='hub/src/content/research/solar-alignment/files/Lectures/01.md';assert.equal(readOwnerModel(draft).documents[0].metadata.title,'First lecture');assert.equal(readOwnerModel(draft).entries.research[0].metadata.documents.length,1);const updates=updateDocumentChanges(draft,{path:notePath,metadata:{title:'Updated lecture'},body:'Updated $E$.'}),updated=applyDraftToSnapshot(draft,updates);assert.equal(readOwnerModel(updated).entries.research[0].metadata.documents[0].title,'Updated lecture');assert.throws(()=>deleteDocumentChanges(updated,{path:notePath,confirmation:'Wrong'}),/exact reading note/);const deletions=deleteDocumentChanges(updated,{path:notePath,confirmation:'Updated lecture'}),deleted=applyDraftToSnapshot(updated,deletions);assert.equal(readOwnerModel(deleted).documents.length,0);assert.equal(readOwnerModel(deleted).entries.research[0].metadata.documents.length,0);assert.ok(deleted.files.some(f=>f.path==='hub/public/uploads/research/solar-alignment/Lectures/01.md'));});
test('HTML comment boundary tricks and active declared MIME cannot bypass upload rules',()=>{assert.throws(()=>createEntryChanges(snapshot(),{kind:'research',slug:'comment-test',metadata:data,body:'<!--><script>alert(1)</script><!-- -->'}),/Raw HTML/);assert.throws(()=>validateAsset('hub/public/uploads/files/readme.txt',utf8Bytes('A harmless-looking preamble'), 'text/html'),/MIME/);assert.throws(()=>createEntryChanges(snapshot(),{kind:'projects',slug:'unsafe-link',metadata:{...data,demoUrl:'javascript:run()'},body:'Overview'}),/Unsafe/);});
test('moving an asset referenced by MDX safely converts the article and preserves its source',()=>{const source=snapshot();source.files[2]=file('hub/src/content/research/solar-alignment/index.mdx',serializeContentDocument({metadata:data,body:"import Figure from '../../../components/Figure.astro';\n\n<Figure src=\"/uploads/images/old.png\" alt=\"Original\" />\n"}));source.files.push({path:'hub/public/uploads/images/old.png',sha:'image',encoding:'base64',content:encodeBase64(new Uint8Array([137,80,78,71,13,10,26,10]))});const changes=moveAssetChanges(source,{from:'hub/public/uploads/images/old.png',to:'hub/public/uploads/images/new.png',confirmation:'old.png'});validateChangeSet(changes,{snapshotFiles:source.files});assert.match(changes.find(c=>c.path==='hub/src/content/research/solar-alignment/index.md').content,/\/uploads\/images\/new.png/);assert.ok(changes.some(c=>c.path.endsWith('/owner-originals/research/solar-alignment/index.mdx')));});
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'owner-cms-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));for(const f of snapshot().files){const dest=path.join(root,...f.path.slice(4).split('/'));await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,f.content);}return root;}
test('local publish applies a complete batch and rejects concurrent baseline',async t=>{const root=await fixture(t),base=await localOwnerSnapshot(root),changes=[...updateDataChanges(base,{profile:{...profile,bio:'Updated biography.'}}),...createEntryChanges(base,{kind:'projects',metadata:{...data,title:'Local project'}})];const results=await Promise.allSettled([applyLocalOwnerPublish(root,{expectedHead:base.head,changes}),applyLocalOwnerPublish(root,{expectedHead:base.head,changes})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='fulfilled').value.phase,'saved-local');assert.equal(results.find(r=>r.status==='rejected').reason.statusCode,409);assert.equal(readOwnerModel(await localOwnerSnapshot(root)).entries.projects.length,1);});
test('local publish rolls back earlier writes when a later filesystem operation fails',async t=>{const root=await fixture(t);await fs.mkdir(path.join(root,'src/content/projects/blocked/index.md'),{recursive:true});const base=await localOwnerSnapshot(root),original=await fs.readFile(path.join(root,'src/data/profile.yaml'),'utf8');const changes=[...updateDataChanges(base,{profile:{...profile,bio:'This must roll back.'}}),...createEntryChanges(base,{kind:'projects',slug:'blocked',metadata:{...data,title:'Blocked'}})];await assert.rejects(applyLocalOwnerPublish(root,{expectedHead:base.head,changes}));assert.equal(await fs.readFile(path.join(root,'src/data/profile.yaml'),'utf8'),original);});
test('developer edits made during transaction preparation are preserved',async t=>{const root=await fixture(t),base=await localOwnerSnapshot(root),changes=updateDataChanges(base,{profile:{...profile,bio:'Owner draft'}}),dest=path.join(root,'src/data/profile.yaml');await assert.rejects(applyLocalOwnerPublish(root,{expectedHead:base.head,changes},{beforeApply:()=>fs.writeFile(dest,'Concurrent developer edit')}),error=>error.statusCode===409);assert.equal(await fs.readFile(dest,'utf8'),'Concurrent developer edit');});
test('local publish refuses directory junctions even when target files are allowlisted',async t=>{const root=await fixture(t),external=path.join(root,'outside');await fs.mkdir(external);await fs.mkdir(path.join(root,'src/content/projects'),{recursive:true});await fs.symlink(external,path.join(root,'src/content/projects/junction'),'junction');const base=await localOwnerSnapshot(root),changes=createEntryChanges(base,{kind:'projects',slug:'junction',metadata:{...data,title:'Junction'}});await assert.rejects(applyLocalOwnerPublish(root,{expectedHead:base.head,changes}),/Symbolic link or junction/);assert.deepEqual(await fs.readdir(external),[]);});
test('real HTTP local APIs require Origin, loopback and CSRF; retries do not save twice',async t=>{const root=await fixture(t),middleware=createOwnerMiddleware({root,token:'test-owner-token'}),server=http.createServer((req,res)=>middleware(req,res,()=>{res.statusCode=404;res.end();}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const origin=`http://127.0.0.1:${server.address().port}`;const session=await fetch(`${origin}/api/owner/session/`).then(r=>r.json());assert.equal(session.mode,'local');assert.equal(session.owner.id,'local');const rpc=(method,params={},headers={})=>fetch(`${origin}/api/owner/rpc/`,{method:'POST',headers:{'content-type':'application/json',origin,'x-owner-csrf':'test-owner-token',...headers},body:JSON.stringify({method,params})});assert.equal((await rpc('snapshot',{}, {'x-owner-csrf':'wrong'})).status,403);assert.equal((await rpc('snapshot',{}, {origin:'https://evil.example'})).status,403);const base=await rpc('snapshot').then(r=>r.json()),params={expectedHead:base.head,changes:updateDataChanges(base,{profile:{...profile,bio:'Saved once.'}}),idempotencyKey:'stable-request-1'};const first=await rpc('publish',params).then(r=>r.json()),retry=await rpc('publish',params).then(r=>r.json());assert.equal(first.phase,'saved-local');assert.equal(retry.head,first.head);assert.equal((await rpc('publish',{...params,message:'different'})).status,409);const hostileHost=await new Promise((resolve,reject)=>{const request=http.get(`${origin}/api/owner/session/`,{headers:{Host:'evil.example'}},response=>{response.resume();resolve(response.statusCode);});request.on('error',reject);});assert.equal(hostileHost,403);});
