import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { importFolder } from '../scripts/lib/importer.mjs';
import { validateContent } from '../scripts/validate-content.mjs';

test('a real folder import retains names and nested relative links, then passes source validation', async t => {
  const fixture = await mkdtemp(path.join(os.tmpdir(), 'academic-import-validation-'));
  t.after(() => rm(fixture, { recursive: true, force: true }));
  const root = path.join(fixture, 'site');
  const source = path.join(fixture, 'research');
  await mkdir(path.join(root, 'src', 'data'), { recursive: true });
  await writeFile(path.join(root, 'src', 'data', 'profile.yaml'), 'name: Z-hang\ndisplayName: Z-hang\nbio: Student\nuniversity: Peking University\ndegree: Space Physics\nsecondDegree: Computer Science\nlastUpdated: 2026-10-02\n');
  await mkdir(path.join(source, 'Figures'), { recursive: true });
  await mkdir(path.join(source, 'Homework'), { recursive: true });
  await mkdir(path.join(source, 'Chapter'), { recursive: true });
  const readme = '# Working research\n\nWorking notes with [lecture](Lecture01.md).\n';
  await writeFile(path.join(source, 'README.md'), readme);
  await writeFile(path.join(source, 'Lecture01.md'), '# Lecture\n\n![Scientific plot](<Figures/图 01.png>)\n\n[Homework](Homework/HW01.md)\n');
  await writeFile(path.join(source, 'Homework', 'HW01.md'), '# Homework\n\n[Lecture](../Lecture01.md)\n');
  await writeFile(path.join(source, 'Chapter', 'index.md'), '# Chapter overview\n\n[Lecture](../Lecture01.md)\n');
  await writeFile(path.join(source, 'Extra.mdx'), '# MDX source\n\nexport const x = 1;\n\n<div>Plain source display</div>\n');
  await writeFile(path.join(source, 'Figures', '图 01.png'), 'image fixture');
  await writeFile(path.join(source, 'raw.fits'), 'raw scientific data');
  await writeFile(path.join(source, '.env'), 'SECRET=private');
  const imported = await importFolder({ root, source, kind: 'research', metadata: { title: 'Working research', date: '2026-10-01', updated: '2026-10-02' } });
  assert.equal(imported.slug, 'working-research');
  assert.ok(imported.omitted.some(item => item.path === 'raw.fits'));
  assert.ok(imported.omitted.some(item => item.path === '.env'));
  assert.equal(await readFile(path.join(source, 'README.md'), 'utf8'), readme);
  const lecture = await readFile(path.join(imported.contentPath, 'files', 'Lecture01.md'), 'utf8');
  assert.ok(lecture.includes('/uploads/research/working-research/Figures/%E5%9B%BE%2001.png'));
  const result = await validateContent(root);
  assert.deepEqual(result.errors, []);
  assert.equal(result.entries.filter(entry => entry.collection === 'documents').length, 5);
  assert.equal(result.entries.filter(entry => entry.collection === 'research').length, 1);
  const oldIndex = await readFile(path.join(imported.contentPath, 'index.md'), 'utf8');
  await assert.rejects(importFolder({ root, source, kind: 'research', metadata: { title: 'Working research' } }), /already exists/);
  assert.equal(await readFile(path.join(imported.contentPath, 'index.md'), 'utf8'), oldIndex);
});
