import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {localDatabase} from '../local-runtime.mjs';
import {createWorker} from '../server.mjs';
const origin='https://archive.example',worker=createWorker({});
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const objects=new Map();return {DB:localDatabase(sql),BUCKET:{async put(key,body){const bytes=body instanceof Uint8Array?body:new Uint8Array(await new Response(body).arrayBuffer());objects.set(key,bytes);return {size:bytes.length}},async get(key){const bytes=objects.get(key);return bytes?{body:bytes,size:bytes.length}:null},async delete(key){objects.delete(key)}},objects};}
function request(path,method='GET',body,owner=true,source=origin){return new Request(origin+path,{method,headers:{Origin:source,...(owner?{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'z-hang729@outlook.com'}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}
async function json(env,path,method='GET',body){const r=await worker.fetch(request(path,method,body),env);const value=await r.json();assert.ok(r.ok,value.error);return value;}
async function folder(env,parentId,name,description='',reuseExisting=false){return (await json(env,'/api/archive/folders','POST',{parentId,name,description,reuseExisting})).entry;}
function upload(folderId,name,body,id=crypto.randomUUID()){const params=new URLSearchParams({folder:folderId,name,size:body.length,id});return new Request(origin+'/api/archive/upload?'+params,{method:'PUT',headers:{Origin:origin,'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'z-hang729@outlook.com','Content-Type':'application/octet-stream'},body});}
test('independent roots, nested folders, editable descriptions and stale-edit protection',async()=>{const env=fixture();assert.equal((await json(env,'/api/archive')).initialized,false);await json(env,'/api/archive/init','POST');const physics=await folder(env,'notes-root','物理','课程目录');const electrodynamics=await folder(env,physics.id,'电动力学');await folder(env,electrodynamics.id,'讲义与推导');const listing=await json(env,'/api/archive?section=notes&folder='+electrodynamics.id);assert.deepEqual(listing.breadcrumbs.map(x=>x.name),['学习笔记','物理','电动力学']);assert.equal(listing.entries[0].name,'讲义与推导');assert.equal((await json(env,'/api/archive?section=research')).entries.length,0);await json(env,'/api/archive/folders/'+electrodynamics.id,'PATCH',{name:'电动力学',description:'Maxwell 方程\n边界条件',revision:0});assert.equal((await json(env,'/api/archive?section=notes&folder='+electrodynamics.id)).folder.description,'Maxwell 方程\n边界条件');assert.equal((await worker.fetch(request('/api/archive/folders/'+electrodynamics.id,'PATCH',{name:'覆盖',description:'',revision:0}),env)).status,409);await json(env,'/api/archive/init','POST');assert.equal((await json(env,'/api/archive?section=notes')).entries.filter(x=>x.name==='物理').length,1);});
test('duplicates and unsafe paths are rejected; reuse keeps description',async()=>{const env=fixture();await json(env,'/api/archive/init','POST');const a=await folder(env,'research-root','项目 A','已有简介');assert.equal((await folder(env,'research-root','项目 A','',true)).description,'已有简介');for(const name of ['项目 A','../逃出','a/b','..'])assert.ok((await worker.fetch(request('/api/archive/folders','POST',{parentId:'research-root',name}),env)).status>=400);assert.equal((await worker.fetch(request('/api/archive/folders','POST',{parentId:a.id,name:'新目录'},false),env)).status,403);assert.equal((await worker.fetch(request('/api/archive/folders','POST',{parentId:a.id,name:'新目录'},true,'https://wrong.example'),env)).status,403);});
test('file bytes and original Unicode name survive download; duplicates never overwrite',async()=>{const env=fixture();await json(env,'/api/archive/init','POST');const f=await folder(env,'notes-root','量子力学');const body=new Uint8Array([0,1,2,255]);const req=upload(f.id,"实验 '数据'.bin",body);const saved=await worker.fetch(req.clone(),env);assert.equal(saved.status,201);const entry=(await saved.json()).entry;assert.equal((await worker.fetch(req.clone(),env)).status,200);assert.equal((await worker.fetch(upload(f.id,"实验 '数据'.bin",new Uint8Array([9])),env)).status,409);const download=await worker.fetch(request('/api/archive/files/'+entry.id),env);assert.deepEqual(new Uint8Array(await download.arrayBuffer()),body);assert.match(download.headers.get('Content-Disposition'),/filename\*=UTF-8/);assert.equal(env.objects.size,1);const empty=await worker.fetch(upload(f.id,'空文件.txt',new Uint8Array()),env);assert.equal(empty.status,201);assert.equal((await json(env,'/api/archive?section=notes&folder='+f.id)).entries.length,2);});
test('concurrent same-name uploads retain one original and clean unlinked objects',async()=>{const env=fixture();await json(env,'/api/archive/init','POST');const replies=await Promise.all([worker.fetch(upload('notes-root','same.txt',new Uint8Array([1])),env),worker.fetch(upload('notes-root','same.txt',new Uint8Array([2])),env)]);assert.deepEqual(replies.map(r=>r.status).sort(),[201,409]);assert.equal(env.objects.size,1);});
test('partial storage failure leaves no listed file and can be retried',async()=>{const env=fixture();await json(env,'/api/archive/init','POST');const put=env.BUCKET.put;env.BUCKET.put=async()=>{throw Error('temporary unavailable')};const request=upload('research-root','研究.pdf',new Uint8Array([37,80,68,70]));assert.equal((await worker.fetch(request.clone(),env)).status,503);assert.equal((await json(env,'/api/archive?section=research')).entries.length,0);env.BUCKET.put=put;assert.equal((await worker.fetch(request.clone(),env)).status,201);const invalid=upload('research-root','过大.bin',new Uint8Array());const u=new URL(invalid.url);u.searchParams.set('size','60000000');assert.equal((await worker.fetch(new Request(u,{method:'PUT',headers:invalid.headers,body:new Uint8Array()}),env)).status,413);});
