import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createWorker,defaults} from '../server.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+file,'utf8'));return {DB:{prepare(query){let args=[];return {bind(...values){args=values;return this;},async first(){return sql.prepare(query).get(...args)||null;},async run(){const result=sql.prepare(query).run(...args);return {meta:{changes:Number(result.changes)}};}}}}};}
const worker=createWorker({'index.html':{body:'home',type:'text/html'},'archive.html':{body:'archive',type:'text/html'}});
const origin='https://profile.example';
function put(profile,revision,email='z-hang729@outlook.com',source=origin){return new Request(origin+'/api/profile',{method:'PUT',headers:{'Content-Type':'application/json','Origin':source,'oai-authenticated-user-id':'site-user','oai-authenticated-user-email':email},body:JSON.stringify({profile,revision})});}
test('profile persists across requests, supports update and rejects stale edits',async()=>{const env=fixture();const profile={...defaults,name:'新的名字',bio:'中文与 English\n第二段'};assert.equal((await worker.fetch(put(profile,0),env)).status,200);const read=await (await worker.fetch(new Request(origin+'/api/profile'),env)).json();assert.deepEqual(read.profile,profile);assert.equal(read.revision,1);assert.equal(read.canEdit,false);assert.equal((await worker.fetch(put({...profile,accent:'wine'},1),env)).status,200);assert.equal((await worker.fetch(put(defaults,1),env)).status,409);assert.equal((await (await worker.fetch(new Request(origin+'/api/profile'),env)).json()).profile.accent,'wine');});
test('only the owner with a same-origin request can save',async()=>{const env=fixture();assert.equal((await worker.fetch(put(defaults,0,'visitor@example.com'),env)).status,403);assert.equal((await worker.fetch(put(defaults,0,undefined,'https://evil.example'),env)).status,403);assert.equal((await worker.fetch(put({...defaults,bio:''},0),env)).status,400);assert.equal((await worker.fetch(put({...defaults,width:'9999'},0),env)).status,400);assert.equal((await (await worker.fetch(new Request(origin+'/api/profile'),env)).json()).revision,0);});
test('home and archive routes, and missing storage fails visibly',async()=>{assert.equal(await (await worker.fetch(new Request(origin+'/'),{})).text(),'home');assert.equal(await (await worker.fetch(new Request(origin+'/archive'),{})).text(),'archive');assert.equal((await worker.fetch(new Request(origin+'/missing'),{})).status,404);assert.equal((await worker.fetch(new Request(origin+'/api/profile'),{})).status,503);});
