import type { APIRoute } from 'astro';
import { allEntries, entryPath, escapeXML, getDocuments, tagSlug } from '../lib/content';
import { url } from '../lib/site';
import {getFiles} from '../lib/file-records';
import {stableFilePath} from '../lib/files.mjs';
import {getCollection} from 'astro:content';
import {logPath} from '../lib/research.mjs';
import {readAcademicRecords} from '../lib/academic-records.mjs';
export const GET: APIRoute = async ({ site }) => {
  if (!site) throw new Error('SITE_URL is required to generate the sitemap.');
  const entries = await allEntries();
  const staticPaths = ['/', '/research/', '/notes/', '/projects/', '/about/', '/cv/', '/publications/', '/search/', '/tags/', '/changelog/','/academic/','/figures/','/references/','/activity/','/packages/'];
  const tags = [...new Set(entries.flatMap((entry) => entry.data.tags.map(tagSlug)))].map((tag) => `/tags/${tag}/`);
  const documents = (['research', 'notes', 'projects'] as const).flatMap((kind) => getDocuments(kind).map((document) => `/${kind}/${document.slug}/`));
  const files=getFiles();
  const logs=await getCollection('logs');
  const academicPaths=['figures','references','packages'].flatMap(kind=>readAcademicRecords(kind).map(record=>`/${kind}/${record.id.split(':')[1]}/`));
  const paths = [...staticPaths,'/files/', ...academicPaths,...tags, ...documents, ...entries.map(entryPath),...logs.map(log=>logPath(log)),...files.map(file=>stableFilePath(file.id))];
  const timestamps = new Map(entries.map((entry) => [entryPath(entry), entry.data.updated.toISOString().slice(0, 10)]));
  for(const file of files)timestamps.set(stableFilePath(file.id),file.updatedAt.slice(0,10));
  for(const log of logs)timestamps.set(logPath(log),(log.data.updated||log.data.date).toISOString().slice(0,10));
  const xml = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...new Set(paths)].map((path) => `<url><loc>${escapeXML(new URL(url(path), site).href)}</loc>${timestamps.has(path) ? `<lastmod>${timestamps.get(path)}</lastmod>` : ''}</url>`).join('')}</urlset>`;
  return new Response(xml, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
