import {STORAGE_LIMITS} from '../lib/files.mjs';
import {readPreviewBytes,parseFITSHeader,fitsImageLayout,parseFITSImage} from './parsers.mjs';
import {node,toolbar,button} from './dom.js';
import {imageControls} from './image-viewer.js';
export async function renderFITSViewer({file,src,host,status}) {
 const first=await readPreviewBytes(src,{limit:STORAGE_LIMITS.previewTableBytes}),header=parseFITSHeader(first.bytes),table=node('table',undefined,{class:'file-fits-metadata'}),body=node('tbody');
 for(const [key,value]of [['Filename',file.originalName],['Dimensions',header.dimensions.join(' × ')],['Axis order',header.axisOrder],['BITPIX',header.bitpix],['NAXIS',header.values.NAXIS],['NAXIS1',header.values.NAXIS1],['NAXIS2',header.values.NAXIS2],['Observation date',header.date],['Instrument',header.instrument],['Telescope',header.telescope],['Exposure',header.exposure],['Units',header.values.BUNIT]])if(value!==undefined&&value!==''){const row=node('tr');row.append(node('th',key,{scope:'row'}),node('td',value));body.append(row);}table.append(body);
 const detail=node('details'),summary=node('summary','FITS header cards');detail.append(summary,node('pre',header.cards.join('\n')));host.append(table,detail);
 if(!header.ended){status.textContent='Header preview truncated; download the original for all HDUs.';return;}
 const layout=fitsImageLayout(header);if(!layout){status.textContent='Header preview only. Image previews support primary 2D HDUs up to 1,048,576 pixels and 8 MB of pixel data; the original is unchanged.';return;}
 const load=button('Load 2D image preview',async()=>{load.disabled=true;try{const source=first.bytes.length>=layout.end?first.bytes:(await readPreviewBytes(src,{limit:layout.end})).bytes,image=parseFITSImage(source,header);await renderImage(image,host,file);load.remove();status.textContent=`Primary 2D image; FITS axis 2 increases upward. ${image.precisionWarning?'64-bit integers are approximated as browser numbers. ':''}Original pixel values remain unchanged.`;}catch(error){status.textContent=error.message;load.disabled=false;}});
 host.append(load);status.textContent='FITS header loaded. Load the bounded primary 2D image separately.';
}
async function renderImage(image,host,file){const controls=toolbar(),stretch=node('select',undefined,{'aria-label':'FITS stretch'}),minimum=node('input',undefined,{type:'number',step:'any',value:image.min,'aria-label':'FITS minimum'}),maximum=node('input',undefined,{type:'number',step:'any',value:image.max,'aria-label':'FITS maximum'}),pixel=node('p','Move over the image for coordinates and pixel values.',{class:'file-fits-pixel','aria-live':'polite'}),surface=node('div',undefined,{class:'file-visual-surface file-fits-surface'}),canvas=node('canvas',undefined,{width:image.width,height:image.height,'aria-label':'FITS grayscale image'}),context=canvas.getContext('2d'),bitmap=context.createImageData(image.width,image.height);
 for(const [value,label]of [['linear','Linear stretch'],['log','Log stretch']])stretch.append(node('option',label,{value}));controls.append(stretch,node('label','Min'),minimum,node('label','Max'),maximum,button('Reset range',()=>{minimum.value=String(image.min);maximum.value=String(image.max);draw();}));surface.append(canvas);host.append(controls,imageControls(surface,canvas,image,file),surface,pixel);
 function draw(){let min=Number(minimum.value),max=Number(maximum.value);if(!Number.isFinite(min)||!Number.isFinite(max)||max<min){pixel.textContent='Choose finite minimum and maximum values, with maximum ≥ minimum.';return;}const range=max-min||1;for(let y=0;y<image.height;y++)for(let x=0;x<image.width;x++){const value=image.data[y*image.width+x],unit=Math.max(0,Math.min(1,(value-min)/range)),gray=Number.isFinite(value)?Math.round((stretch.value==='log'?Math.log1p(1000*unit)/Math.log1p(1000):unit)*255):0,offset=((image.height-1-y)*image.width+x)*4;bitmap.data[offset]=bitmap.data[offset+1]=bitmap.data[offset+2]=gray;bitmap.data[offset+3]=255;}context.putImageData(bitmap,0,0);}
 stretch.addEventListener('change',draw);minimum.addEventListener('change',draw);maximum.addEventListener('change',draw);canvas.addEventListener('pointermove',event=>{const box=canvas.getBoundingClientRect(),x=Math.floor((event.clientX-box.left)/box.width*image.width),y=image.height-1-Math.floor((event.clientY-box.top)/box.height*image.height);if(x>=0&&x<image.width&&y>=0&&y<image.height)pixel.textContent=`FITS pixel (${x+1}, ${y+1}): ${image.data[y*image.width+x]}`;});draw();
}
