import {compareFiles,folderDownloadMode,folderManifest} from './library-model.mjs';
const report=(el,text)=>{const status=el.closest('[data-file-detail],.file-resources,[data-file-library]')?.querySelector('[data-file-status]');if(status)status.textContent=text;};
document.querySelectorAll('[data-file-copy],[data-file-copy-text]').forEach(button=>button.addEventListener('click',async()=>{const text=button.dataset.fileCopyText??new URL(button.dataset.fileCopy,location.origin).href;try{await navigator.clipboard.writeText(text);report(button,button.dataset.fileCopyText?'Citation copied.':'File page link copied.');}catch{report(button,`Copy ${button.dataset.fileCopyText?'this text':'this link'}: ${text}`);}}));
const library=document.querySelector('[data-file-library]');
if(library){
 const search=library.querySelector('[data-file-search]'),filters=[...library.querySelectorAll('[data-library-filter]')],sort=library.querySelector('[data-library-sort]'),cards=[...library.querySelectorAll('[data-file-card]')],container=library.querySelector('[data-library-cards]'),count=library.querySelector('[data-library-count]'),empty=library.querySelector('[data-library-empty]'),views=[...library.querySelectorAll('[data-library-view-button]')];
 const normalize=value=>String(value||'').normalize('NFKC').toLocaleLowerCase(),query=new URL(location.href).searchParams;
 search.value=query.get('q')||'';
 for(const field of filters){const value=query.get(field.dataset.libraryFilter);if(value&&[...field.options].some(option=>option.value===value))field.value=value;}
 if(['updated','added','name','size'].includes(query.get('sort')))sort.value=query.get('sort');
 function setView(view){if(!['grid','list','folders'].includes(view))view='grid';library.dataset.libraryView=view;views.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.libraryViewButton===view)));if(view==='folders'){const tree=library.querySelector('[data-library-tree]');if(tree)tree.open=true;}try{sessionStorage.setItem('zh-library-view',view);}catch{}}
 try{setView(query.get('view')||sessionStorage.getItem('zh-library-view')||'grid');}catch{setView('grid');}
 function updateURL(){const next=new URL(location.href);for(const key of ['q','group','category','folder','tag','days','sort','view'])next.searchParams.delete(key);if(search.value.trim())next.searchParams.set('q',search.value.trim());for(const field of filters)if(field.value)next.searchParams.set(field.dataset.libraryFilter,field.value);if(sort.value!=='updated')next.searchParams.set('sort',sort.value);if(library.dataset.libraryView!=='grid')next.searchParams.set('view',library.dataset.libraryView);history.replaceState(null,'',next);}
 function apply(){
  const values=Object.fromEntries(filters.map(field=>[field.dataset.libraryFilter,field.value])),terms=normalize(search.value).trim().split(/\s+/).filter(Boolean),visible=new Set();
  for(const card of cards){const data=card.dataset,group=data.fileGroup,folder=data.fileFolder,tags=JSON.parse(data.fileTags||'[]');const matches=terms.every(term=>normalize(data.fileName).includes(term))&&(!values.group||values.group===group||(values.group==='documents'&&group==='pdf'))&&(!values.category||(data.fileCategories||data.fileCategory).split(' ').includes(values.category))&&(!values.folder||folder===values.folder||folder.startsWith(values.folder+'/'))&&(!values.tag||tags.some(tag=>normalize(tag)===normalize(values.tag)))&&(!values.days||Date.parse(data.fileUpdated)>=Date.now()-Number(values.days)*86400000);card.hidden=!matches;if(matches)visible.add(data.fileId);}
  library.querySelectorAll('[data-file-tree-item]').forEach(item=>item.hidden=!visible.has(item.dataset.fileTreeItem));
  [...library.querySelectorAll('[data-file-tree-branch]')].reverse().forEach(branch=>branch.hidden=![...branch.querySelectorAll('[data-file-tree-item]')].some(item=>!item.hidden));
  count.textContent=`${visible.size} of ${cards.length} ${cards.length===1?'file':'files'}`;empty.hidden=visible.size>0||cards.length===0;container.hidden=visible.size===0;updateURL();
 }
 function order(){const record=card=>({displayName:card.dataset.fileDisplayName,size:Number(card.dataset.fileSize),updatedAt:card.dataset.fileUpdated,uploadedAt:card.dataset.fileAdded});cards.sort((a,b)=>compareFiles(record(a),record(b),sort.value)).forEach(card=>container.append(card));}
 let frame;search.addEventListener('input',()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(apply);});filters.forEach(field=>field.addEventListener('change',apply));sort.addEventListener('change',()=>{order();apply();});views.forEach(button=>button.addEventListener('click',()=>{setView(button.dataset.libraryViewButton);updateURL();}));library.querySelectorAll('[data-library-reset]').forEach(button=>button.addEventListener('click',()=>{search.value='';filters.forEach(field=>field.value='');apply();search.focus();}));order();apply();if(query.get('focus')==='search')requestAnimationFrame(()=>search.focus());
}
const saveBlob=(blob,name)=>{const href=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=href;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(href),60000);};
const saveManifest=(files,name)=>saveBlob(new Blob([JSON.stringify(folderManifest(files,{name,origin:location.origin}),null,2)],{type:'application/json'}),`${name.replace(/[\\/:*?"<>|]/g,'-')||'folder'}-manifest.json`);
document.querySelectorAll('[data-folder-download]').forEach(button=>button.addEventListener('click',async()=>{
 const files=JSON.parse(button.dataset.folderDownload),name=button.dataset.folderName||'folder';let stream;
 if(folderDownloadMode(files)==='manifest'){saveManifest(files,name);report(button,'File manifest downloaded with stable page links, original download URLs and checksums. Use the uploaded ZIP snapshot when available, or download originals individually.');return;}
 try{if('showSaveFilePicker'in window){const handle=await window.showSaveFilePicker({suggestedName:`${name.replace(/[\\/:*?"<>|]/g,'-')}.zip`,types:[{description:'ZIP archive',accept:{'application/zip':['.zip']}}]});stream=await handle.createWritable();}
 button.disabled=true;const {ZipWriter,BlobWriter,HttpReader}=await import('@zip.js/zip.js');const writer=new ZipWriter(stream||new BlobWriter('application/zip'),{useWebWorkers:false});let done=0;
 for(const file of files){report(button,`Downloading folder: ${++done}/${files.length}`);await writer.add(file.name,new HttpReader(file.url,{useRangeHeader:true,forceRangeRequests:false}),{level:0});}
 const blob=await writer.close();if(!stream)saveBlob(blob,`${name.replace(/[\\/:*?"<>|]/g,'-')}.zip`);report(button,'Folder download complete.');
 }catch(error){await stream?.abort?.().catch(()=>{});if(error.name!=='AbortError'){saveManifest(files,name);report(button,`Folder ZIP unavailable: ${error.message}. A file manifest has been downloaded; original downloads remain available.`);}}finally{button.disabled=false;}
}));
