import {node,toolbar,button,downloadLink,fullscreenButton} from './dom.js';
import workerURL from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
export async function renderPDFViewer({file,src,host,status,base}) {
 // Rendering a large PDF requires real range support; never silently buffer it all.
 if(file.size>32*1024*1024){const probe=await fetch(src,{headers:{Range:'bytes=0-0'},credentials:'omit'});await probe.body?.cancel();if(probe.status!==206||!/^bytes 0-0\//.test(probe.headers.get('content-range')||''))throw new Error('This server cannot stream PDF byte ranges. Preview is limited to 32 MB here; download the original PDF.');}
 const pdfjs=await import('pdfjs-dist/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=workerURL;
 const assets=`${base.replace(/\/$/,'')}/vendor/pdfjs/${pdfjs.version}/`,loading=pdfjs.getDocument({url:src,withCredentials:false,disableAutoFetch:true,disableStream:true,rangeChunkSize:256*1024,isEvalSupported:false,enableXfa:false,stopAtErrors:true,maxImageSize:16*1024*1024,canvasMaxAreaInBytes:64*1024*1024,cMapUrl:assets+'cmaps/',cMapPacked:true,standardFontDataUrl:assets+'standard_fonts/',wasmUrl:assets+'wasm/',iccUrl:assets+'iccs/'});
 loading.onPassword=()=>{loading.destroy();status.textContent='This PDF needs a password. Download it and open it in your PDF application.';};
 const document=await loading.promise,controls=toolbar(),previous=button('Previous page',()=>request(pageNumber-1)),next=button('Next page',()=>request(pageNumber+1)),page=node('input',undefined,{type:'number',min:'1',max:document.numPages,value:'1','aria-label':'PDF page number'}),counter=node('span',`/ ${document.numPages}`),zoom=node('select',undefined,{'aria-label':'PDF zoom'}),surface=node('div',undefined,{class:'file-pdf-surface file-visual-surface'}),canvas=node('canvas',undefined,{'aria-label':'PDF page 1'});let pageNumber=1,rendering=null,serial=0,currentPage=null;
 for(const [value,label]of [['fit','Fit width'],['0.5','50%'],['0.75','75%'],['1','100%'],['1.5','150%'],['2','200%'],['3','300%']])zoom.append(node('option',label,{value}));
 controls.append(previous,node('span','Page'),page,counter,next,zoom,fullscreenButton(host),downloadLink(file));surface.append(canvas);host.append(controls,surface);
 function report(error){if(error?.name==='RenderingCancelledException')return;status.textContent='Preview unavailable: '+error.message+'. Download the original PDF.';}
 async function request(number){number=Math.floor(Number(number));if(!Number.isFinite(number)||number<1||number>document.numPages){page.value=String(pageNumber);return;}const version=++serial;pageNumber=number;page.value=String(number);previous.disabled=number===1;next.disabled=number===document.numPages;rendering?.cancel();try{const selected=await document.getPage(number);if(version!==serial)return;if(currentPage&&currentPage!==selected)currentPage.cleanup();currentPage=selected;const natural=selected.getViewport({scale:1}),scale=zoom.value==='fit'?Math.max(0.1,(surface.clientWidth-24)/natural.width):Number(zoom.value),viewport=selected.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2,Math.sqrt(16*1024*1024/(viewport.width*viewport.height))),width=Math.ceil(viewport.width*ratio),height=Math.ceil(viewport.height*ratio);canvas.width=width;canvas.height=height;canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;canvas.setAttribute('aria-label',`PDF page ${number} of ${document.numPages}`);rendering=selected.render({canvasContext:canvas.getContext('2d'),canvas,viewport,transform:ratio===1?null:[ratio,0,0,ratio,0,0],annotationMode:pdfjs.AnnotationMode.DISABLE});await rendering.promise;if(version===serial)status.textContent=`Page ${number} of ${document.numPages}. PDF preview is read only.`;}catch(error){report(error);}}
 page.addEventListener('change',()=>request(page.value));zoom.addEventListener('change',()=>request(pageNumber));let resizeTimer;const observer=new ResizeObserver(()=>{if(zoom.value==='fit'){clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>request(pageNumber),180);}});observer.observe(surface);
 window.addEventListener('pagehide',()=>{observer.disconnect();rendering?.cancel();loading.destroy();},{once:true});await request(1);
}
