import {STORAGE_LIMITS,previewTypeFor} from '../lib/files.mjs';
import {readPreviewBytes,parseCSV,parseFITSHeader,notebookCells} from './parsers.mjs';
const root=document.querySelector('[data-file-detail]');
const node=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
async function renderText(text,host,extension){const pre=node('pre'),code=node('code',text,{class:`language-${{py:'python',pro:'idl',js:'javascript',ts:'typescript',tex:'latex',yml:'yaml'}[extension]||extension}`});pre.append(code);host.append(pre);const {highlightCodeBlocks}=await import('../owner/highlight.js');await highlightCodeBlocks(host);}
async function renderNotebook(text,host,base){const {renderPreview}=await import('../owner/markdown.js');for(const cell of notebookCells(text)){const block=node('section');if(cell.type==='markdown')await renderPreview(cell.source,block,base);else await renderText(cell.source,block,'py');for(const output of cell.outputs){const plain=output.text||output.data?.['text/plain'];if(plain)block.append(node('pre',Array.isArray(plain)?plain.join(''):String(plain)));for(const mime of ['image/png','image/jpeg','image/webp','image/gif']){const image=output.data?.[mime];if(image){const data=Array.isArray(image)?image.join(''):image;if(data.length<STORAGE_LIMITS.previewTextBytes&&/^[A-Za-z0-9+/=\s]+$/.test(data))block.append(node('img',undefined,{src:`data:${mime};base64,${data}`,alt:'Static notebook output'}));}}}host.append(block);}}
async function load(file,host,status){const type=previewTypeFor(file.originalName,file.mimeType),src=file.previewUrl||file.downloadUrl,base=import.meta.env.BASE_URL;
 if(['download','office'].includes(type)){host.append(node('p',type==='office'?'Download the original and open it in your Office application.':'This type is available as an original download.'));return;}
 if(type==='pdf'){host.append(node('iframe',undefined,{src:`${src}${src.includes('#')?'':'#toolbar=1'}`,title:`PDF preview: ${file.displayName}`,loading:'lazy',referrerpolicy:'no-referrer'}));return;}
 if(type==='image'){const tools=node('div',undefined,{class:'file-image-tools'}),zoom=node('input',undefined,{type:'range',min:'25',max:'300',value:'100','aria-label':'Image zoom'}),label=node('span','100%'),canvas=node('div',undefined,{class:'file-image-canvas'}),image=node('img',undefined,{src,alt:file.displayName,loading:'lazy',referrerpolicy:'no-referrer'});zoom.addEventListener('input',()=>{image.style.maxWidth='none';image.style.width=`${zoom.value}%`;label.textContent=`${zoom.value}%`;});tools.append(node('span','Zoom'),zoom,label);canvas.append(image);host.append(tools,canvas);return;}
 if(['audio','video'].includes(type)){host.append(node(type,undefined,{src,controls:'',preload:'metadata',referrerpolicy:'no-referrer'}));return;}
 const cap=['csv','fits'].includes(type)?STORAGE_LIMITS.previewTableBytes:STORAGE_LIMITS.previewTextBytes;
 const {bytes,truncated}=await readPreviewBytes(src,{limit:cap});const text=new TextDecoder('utf-8',{fatal:type!=='fits'}).decode(bytes,{stream:truncated});
 if(truncated)status.textContent='Showing a bounded preview. Download the original for the complete file.';
 if(type==='fits'){const header=parseFITSHeader(bytes),table=node('table'),body=node('tbody');for(const [key,value]of [['Dimensions',header.dimensions.join(' × ')],['Axis order',header.axisOrder],['BITPIX',header.bitpix],['Observation date',header.date],['Instrument',header.instrument],['Telescope',header.telescope]])if(value){const row=node('tr');row.append(node('th',key),node('td',value));body.append(row);}table.append(body);host.append(table,node('pre',header.cards.join('\n')));if(!header.ended)status.textContent='Header preview truncated; download the original for all HDUs.';return;}
 if(type==='csv'){const rows=parseCSV(text,{delimiter:file.extension==='tsv'?'\t':','}),table=node('table'),body=node('tbody');rows.forEach((cells,index)=>{const row=node('tr');cells.forEach(c=>row.append(node(index?'td':'th',c)));body.append(row);});table.append(body);host.append(table);status.textContent=`Preview: first ${rows.length} rows. Download for the complete table.`;return;}
 if(type==='markdown'){const {renderPreview}=await import('../owner/markdown.js');await renderPreview(text,host,base);return;}
 if(type==='notebook'){if(truncated)throw new Error('This notebook exceeds the static preview budget. Download the original.');await renderNotebook(text,host,base);return;}
 if(type==='json'&&!truncated){await renderText(JSON.stringify(JSON.parse(text),null,2),host,'json');return;}
 await renderText(text,host,file.extension);
}
if(root){const file=JSON.parse(root.dataset.filePreview),host=root.querySelector('[data-preview-host]'),status=root.querySelector('[data-file-status]'),open=root.querySelector('[data-preview-load]'),fullscreen=root.querySelector('[data-preview-fullscreen]');open.addEventListener('click',async()=>{open.disabled=true;status.textContent='Loading preview…';host.replaceChildren();try{await load(file,host,status);if(status.textContent==='Loading preview…')status.textContent='';fullscreen.hidden=false;open.hidden=true;}catch(error){status.textContent=error.message;open.disabled=false;}});fullscreen.addEventListener('click',()=>host.requestFullscreen?.().catch(()=>{}));}
