import {STORAGE_LIMITS} from '../lib/files.mjs';
import {readPreviewBytes} from './parsers.mjs';
import {node,toolbar,copyButton,downloadLink,button} from './dom.js';
export async function renderStructuredViewer({file,src,host,status}) {
 const {bytes,truncated}=await readPreviewBytes(src,{limit:STORAGE_LIMITS.previewTextBytes}),text=new TextDecoder('utf-8',{fatal:true}).decode(bytes,{stream:truncated});
 if(truncated){const {renderCode}=await import('./text-viewer.js');await renderCode(text,host,file.extension,{file});status.textContent='Preview truncated at the text preview limit. A complete JSON/YAML document is needed for the tree; download the original.';return;}
 let value;if(['yaml','yml'].includes(file.extension)){const {parseDocument}=await import('yaml'),document=parseDocument(text,{schema:'core',uniqueKeys:true});if(document.errors.length)throw new Error('YAML preview could not parse this document. Download the original.');value=document.toJS({maxAliasCount:0});}else value=JSON.parse(text);
 let formatted;try{formatted=JSON.stringify(value,null,2);}catch{formatted=text;}
 const controls=toolbar(),tree=node('div',undefined,{class:'file-structured-tree'}),notice=node('p','',{class:'file-viewer-notice'});let rendered=0;
 controls.append(node('span',file.extension.toUpperCase()),copyButton(()=>formatted,'Copy formatted'),downloadLink(file));host.append(controls,tree,notice);
 function item(key,child,depth){if(++rendered>5000){notice.textContent='Tree preview limited to 5,000 fields. Copy or download the complete document.';return null;}const title=key===null?'Root':JSON.stringify(String(key));if(child===null||typeof child!=='object'){const leaf=node('div',undefined,{class:'file-tree-leaf'});leaf.append(node('span',title+': ',{class:'file-tree-key'}),node('span',JSON.stringify(child)??String(child)));return leaf;}if(depth>=32)return node('p',title+': [nested value; download to inspect]');const entries=Object.entries(child),branch=node('details'),summary=node('summary',`${title}: ${Array.isArray(child)?'Array':'Object'} (${entries.length})`),children=node('div',undefined,{class:'file-tree-children'});let loaded=0,initialized=false;branch.append(summary,children);const next=button('Load more fields',()=>appendChildren());function appendChildren(){next.remove();const end=Math.min(loaded+100,entries.length);for(;loaded<end;loaded++){const [name,entry]=entries[loaded],element=item(name,entry,depth+1);if(!element){loaded=entries.length;break;}children.append(element);}if(loaded<entries.length&&rendered<5000)children.append(next);}branch.addEventListener('toggle',()=>{if(branch.open&&!initialized){initialized=true;appendChildren();}});if(depth===0)branch.open=true;return branch;}
 tree.append(item(null,value,0)||node('p','Empty document.'));status.textContent='';
}
