import {STORAGE_LIMITS} from '../lib/files.mjs';
import {readPreviewBytes,parseCSV} from './parsers.mjs';
import {node,toolbar,downloadLink,button} from './dom.js';
export async function renderTableViewer({file,src,host,status}) {
 const {bytes,truncated}=await readPreviewBytes(src,{limit:STORAGE_LIMITS.previewTableBytes}),text=new TextDecoder('utf-8',{fatal:true}).decode(bytes,{stream:truncated}),rows=parseCSV(text,{rows:502,delimiter:file.extension==='tsv'?'\t':',',includePartial:!truncated});
 const headers=rows.shift()||[],data=rows.slice(0,500).map((cells,index)=>({cells,index})),hasMore=truncated||rows.length>500,controls=toolbar(),filter=node('input',undefined,{type:'search',placeholder:'Filter preview rows','aria-label':'Filter table preview'}),count=node('select',undefined,{'aria-label':'Rows displayed'});
 for(const value of [100,500])count.append(node('option',`First ${value} rows`,{value}));controls.append(filter,count,downloadLink(file));
 const surface=node('div',undefined,{class:'file-table-scroll',tabindex:'0'}),table=node('table',undefined,{class:'file-data-table'}),head=node('thead'),body=node('tbody'),heading=node('tr');let sortColumn=-1,ascending=true;
 headers.forEach((title,index)=>{const th=node('th',undefined,{scope:'col'}),sort=button(title||`Column ${index+1}`,()=>{ascending=sortColumn===index?!ascending:true;sortColumn=index;render();},{'aria-label':`Sort by ${title||'column '+(index+1)}`});th.append(sort);heading.append(th);});head.append(heading);table.append(head,body);surface.append(table);host.append(controls,surface);
 function render(){let selected=data.filter(row=>!filter.value||row.cells.some(cell=>cell.toLocaleLowerCase().includes(filter.value.toLocaleLowerCase())));if(sortColumn>=0)selected=[...selected].sort((a,b)=>{const x=a.cells[sortColumn]||'',y=b.cells[sortColumn]||'',numeric=x.trim()!==''&&y.trim()!==''&&Number.isFinite(Number(x))&&Number.isFinite(Number(y)),order=numeric?Number(x)-Number(y):x.localeCompare(y,undefined,{numeric:true});return (ascending?order:-order)||a.index-b.index;});body.replaceChildren();for(const row of selected.slice(0,Number(count.value))){const tr=node('tr');for(let index=0;index<headers.length;index++)tr.append(node('td',row.cells[index]||''));body.append(tr);}for(const [index,th]of [...heading.children].entries())th.setAttribute('aria-sort',index===sortColumn?(ascending?'ascending':'descending'):'none');status.textContent=`Preview: ${Math.min(selected.length,Number(count.value))} rows displayed; ${data.length} data rows loaded${hasMore?' (preview truncated)':''}. Filtering and sorting apply to loaded rows. Download the complete table.`;}
 filter.addEventListener('input',render);count.addEventListener('change',render);render();
}
