import './owner.css';
import './dashboard.css';
import {el,button,inputField,modal,formAction} from './dom.js';
import {connectLocal,connectRemote} from './transport.js';
import {readDraft,saveDraft} from './draft-store.js';
import {publishBatch,classifyPublicationError} from './publication.js';
import {readOwnerModel,applyDraftToSnapshot,mergeDraftChanges,validateDraftChanges,summarizeChanges,suggestCommitMessage,updateDataChanges,updateEntryChanges} from '../lib/owner/model.mjs';
import {openEntry,deleteEntry,openLog,openProfile,openNavigation,openHomepage,openPreview} from './editors.js';
import {installImages} from './images.js';
const base=import.meta.env.BASE_URL.replace(/\/$/,'');
let connection,snapshot,changes=[],undo=[],draftKey,publishKey,pendingPublication=null,confirmedPublication=null,needsRefresh=false,lock=false,editing=false,toast,toolbar,model;
let homepageTemplate,homepageInitialLayout,homepageLastLayout;
let dashboardStatus={head:null,loading:false,result:null,commit:null,error:null};
const backend=()=>document.querySelector('meta[name="owner-backend"]')?.content||document.querySelector('[data-owner-backend]')?.dataset.ownerBackend||'';
const effective=()=>applyDraftToSnapshot(snapshot,changes);
function notice(text){if(!toast){toast=el('div',{class:'owner-notice',role:'status','aria-live':'polite'});document.body.append(toast);}toast.textContent=text;const status=document.querySelector('[data-owner-login-status]');if(status)status.textContent=text;}
async function persist(){await saveDraft(draftKey,{head:snapshot.head,baseline:snapshot,changes,publishKey,pendingPublication,confirmedPublication,updatedAt:new Date().toISOString()});}
async function stage(next){if(lock)throw new Error('Wait for the current publish to finish.');if(pendingPublication)throw new Error('A previous publish needs confirmation. Retry that publication before editing this batch.');if(needsRefresh)throw new Error('Your save succeeded. Reload the workspace to fetch the latest content before editing again.');const merged=mergeDraftChanges(snapshot,changes,next);validateDraftChanges(snapshot,merged);undo.push(structuredClone(changes));changes=merged;publishKey=null;confirmedPublication=null;model=readOwnerModel(effective());await persist();refresh();notice(`${changes.length} file changes saved to your draft. Review and publish when ready.`);}
const ctx={snapshot:effective,model:()=>model,stage,base,notice,refresh,get transport(){return connection;}};
function uploads(options={}){return import('./uploads.js').then(module=>module.openUploads(ctx,options)).catch(error=>notice(error.message));}
function files(){return import('./uploads.js').then(module=>module.openFiles(ctx)).catch(error=>notice(error.message));}
async function cleanupCommittedStorage(result){if(connection.mode!=='github'||result?.phase!=='committed'||pendingPublication)return [];try{const {finalizeStorageDeletes}=await import('./storage.js');const failures=await finalizeStorageDeletes(ctx);return failures.length?['Published successfully. Some removed originals need cleanup retry in File manager.']:[];}catch{return ['Published successfully. Storage cleanup can be retried in File manager.'];}}
function documents(kind,slug,path=null){return import('./documents.js').then(module=>path?module.openDocument(ctx,{kind,slug,path}):module.openDocuments(ctx,{kind,slug})).catch(error=>notice(error.message));}
function safeAction(task){return event=>{event?.preventDefault();event?.stopPropagation();Promise.resolve().then(task).catch(error=>notice(error.message));};}
function editButton(label,task,attrs={}){return button(label,safeAction(task),{class:'owner-control',...attrs});}
function resolvedURL(value){if(!value)return '#';return value.startsWith('/')&&!value.startsWith('//')?base+value:value;}
function previewHomepageLayout(){const root=document.querySelector('[data-owner-homepage]');if(!root)return;const signature=JSON.stringify(model.homepage.sections);if(!homepageTemplate){homepageTemplate=root.cloneNode(true);homepageInitialLayout=JSON.stringify(readOwnerModel(snapshot).homepage.sections);homepageLastLayout=homepageInitialLayout;}if(signature===homepageLastLayout)return;homepageLastLayout=signature;const source=homepageTemplate.cloneNode(true);if(signature===homepageInitialLayout){root.replaceChildren(...source.childNodes);return;}const nodes=new Map([...source.querySelectorAll('[data-owner-section]')].map(node=>[node.dataset.ownerSection,node]));const focus=nodes.get('current-focus');if(focus?.closest('.hero'))focus.remove();const output=[];const sections=[...model.homepage.sections].filter(item=>item.visible).sort((a,b)=>a.order-b.order);for(let index=0;index<sections.length;index++){const section=sections[index],next=sections[index+1];const node=nodes.get(section.id)||el('section',{class:'section','data-owner-section':section.id},el('h2',{},section.title||section.id.replaceAll('-',' ')),el('p',{class:'owner-muted'},'This section will be included when the website rebuilds.'));if(section.id==='hero'&&next?.id==='current-focus'&&nodes.has('current-focus')){node.append(nodes.get('current-focus'));index++;}if(['research-updates','notes'].includes(section.id)){const columns=[node];if(next&&['research-updates','notes'].includes(next.id)&&nodes.has(next.id)){columns.push(nodes.get(next.id));index++;}output.push(el('section',{class:'updates-section'+(columns.length>1?' two-column':'')},...columns));}else output.push(node);}root.replaceChildren(...output);}
function renderBindings(){previewHomepageLayout();for(const node of document.querySelectorAll('[data-owner-field]')){if(node.dataset.ownerEditing==='true')continue;const key=node.dataset.ownerField,value=model.profile[key]??'';
  if(['currently','timeline','education'].includes(key)){const children=[];for(const item of value){if(key==='currently')children.push(el('div',{class:'currently-item'},el('span',{},item.label),el('strong',{},item.text)));else if(key==='timeline')children.push(el('div',{class:'timeline-entry'},el('time',{},item.date),el('div',{},el('h3',{},item.title),el('p',{},item.description))));else children.push(el('p',{},[item.start,item.end,item.institution,item.description].filter(Boolean).join(' · ')));}node.replaceChildren(...children);}
  else if(key==='researchInterests')node.replaceChildren(...value.map(text=>el('span',{class:'interest'},text)));
  else if(key==='links')node.replaceChildren(...value.map(item=>el('a',{href:resolvedURL(item.url),target:'_blank',rel:'noopener noreferrer'},item.label||item.title||item.url)));
  else if(node.tagName==='A'){node.href=key==='email'?`mailto:${value}`:resolvedURL(value);if(node.dataset.ownerText==='true')node.textContent=value;}
  else if(node.tagName==='IMG')node.src=resolvedURL(value);
  else if(['email','github','cvPdf'].includes(key)){const anchor=node.querySelector('a');if(anchor)anchor.href=key==='email'?`mailto:${value}`:resolvedURL(value);else if(value)node.replaceChildren(el('a',{class:'button-secondary',href:key==='email'?`mailto:${value}`:resolvedURL(value)},key==='email'?'Send an email':key==='github'?'GitHub':'CV PDF'));else node.replaceChildren();}
  else node.textContent=String(value);
  }
  for(const node of document.querySelectorAll('[data-owner-section]')){const section=model.homepage.sections.find(item=>item.id===node.dataset.ownerSection);if(!section)continue;node.dataset.ownerHidden=String(section.visible===false);if(section.title){const title=node.querySelector('h2');if(title)title.textContent=section.title;}node.style.order=String(section.order||0);}
}
function inlineField(node){const key=node.dataset.ownerField,value=model.profile[key]??'';if(Array.isArray(value)||node.tagName==='A'||node.tagName==='IMG'){openProfile(ctx,key);return;}if(node.dataset.ownerEditing==='true')return;node.dataset.ownerEditing='true';const original=[...node.childNodes],field=inputField('Edit '+key,String(value),{multiline:key.toLowerCase().includes('bio')||String(value).length>120}),status=el('p',{role:'status',class:'owner-muted'});
  const save=button('Save draft',async event=>{event.preventDefault();save.disabled=true;try{const profile={...model.profile,[key]:field.input.value.trim(),lastUpdated:new Date().toISOString().slice(0,10)};await stage(updateDataChanges(effective(),{profile}));node.dataset.ownerEditing='false';renderBindings();}catch(error){status.textContent=error.message;}finally{save.disabled=false;}},{class:'owner-primary'});
  node.replaceChildren(el('span',{class:'owner-inline-editor'},field.node,el('span',{class:'owner-row-actions'},save,button('Cancel',()=>{node.dataset.ownerEditing='false';node.replaceChildren(...original);})),status));field.input.focus();
}
function installInline(){document.body.classList.add('owner-active');
  for(const node of document.querySelectorAll('[data-owner-field]')){if(node.dataset.ownerInstalled)continue;node.dataset.ownerInstalled='true';node.classList.add('owner-editable');const control=editButton('Edit',()=>inlineField(node),{'aria-label':'Edit '+node.dataset.ownerField});control.classList.add('owner-inline-trigger');node.insertAdjacentElement('afterend',control);}
  for(const node of document.querySelectorAll('[data-owner-entry],[data-owner-detail]')){if(node.dataset.ownerInstalled)continue;node.dataset.ownerInstalled='true';const kind=node.dataset.ownerKind,slug=node.dataset.ownerSlug;const tools=el('div',{class:'owner-card-controls'},editButton(node.dataset.ownerDocument?'Edit document':'Edit',()=>node.dataset.ownerDocument?documents(kind,slug,node.dataset.ownerDocument):openEntry(ctx,kind,slug)),editButton('Featured',async()=>{const entry=model.entries[kind].find(item=>item.slug===slug);await stage(updateEntryChanges(effective(),{kind,slug,metadata:{featured:!entry.metadata.featured}}));}),editButton(kind==='notes'?'Notes':'Documents',()=>documents(kind,slug)),editButton('Upload files',()=>uploads({kind,slug})),editButton('Upload folder',()=>uploads({kind,slug,folder:true})),editButton('Delete',()=>deleteEntry(ctx,kind,slug)));if(kind==='research')tools.append(editButton('Add update',()=>openLog(ctx,slug)));node.prepend(tools);}
  for(const node of document.querySelectorAll('[data-owner-archive]')){if(node.dataset.ownerInstalled)continue;node.dataset.ownerInstalled='true';const kind=node.dataset.ownerArchive;node.prepend(el('div',{class:'owner-archive-controls'},editButton('New '+kind,()=>openEntry(ctx,kind)),editButton('Upload files',()=>uploads({kind})),editButton('Upload folder',()=>uploads({kind,folder:true}))));}
  const detail=document.querySelector('[data-owner-detail]:not([data-owner-document])');if(detail){const kind=detail.dataset.ownerKind,slug=detail.dataset.ownerSlug;for(const heading of detail.querySelectorAll('[data-owner-body] h2')){if(heading.dataset.ownerInstalled)continue;heading.dataset.ownerInstalled='true';heading.append(editButton('Edit section',()=>openEntry(ctx,kind,slug,{section:heading.textContent})));}}
  for(const node of document.querySelectorAll('[data-owner-log-path]')){if(node.dataset.ownerInstalled)continue;const log=model.logs.find(item=>item.path===node.dataset.ownerLogPath);if(!log)continue;node.dataset.ownerInstalled='true';node.querySelector('h3')?.append(editButton('Edit update',()=>openLog(ctx,log.metadata.project,log.path)));}
  installImages(ctx);
}
function createToolbar(){toolbar=el('aside',{class:'owner-toolbar','aria-label':'Owner editing toolbar'});toolbar.append(el('strong',{class:'owner-mode-label'},connection.mode==='github'?'OWNER MODE':'LOCAL EDIT'),el('span',{'data-owner-change-count':'',class:'owner-change-count'}),editButton('Profile',()=>openProfile(ctx)),editButton('Add',openAdd),editButton('Upload',()=>uploads()),editButton('Upload folder',()=>uploads({folder:true})),editButton('Files',files),editButton('Undo',async()=>{if(lock){notice('Wait for the current publish to finish.');return;}if(pendingPublication){notice('A previous publish needs confirmation. Retry that publication before undoing this batch.');return;}if(needsRefresh){notice('Your save succeeded. Reload the workspace to fetch the latest content before undoing.');return;}if(!undo.length){notice('There is no earlier draft change in this session.');return;}changes=undo.pop();publishKey=null;model=readOwnerModel(effective());await persist();refresh();notice('Previous draft restored.');},{'data-owner-undo':''}),editButton('Discard',discard),el('a',{href:base+'/owner/',class:'owner-toolbar-link'},'Workspace'),button(connection.mode==='github'?'Review & publish':'Review & save',openReview,{class:'owner-primary','data-owner-review':''}),editButton('Exit',exit));document.body.append(toolbar);}
function openAdd(){const surface=modal('Add to your academic garden');for(const kind of ['research','notes','projects'])surface.body.append(button('New '+kind,()=>{surface.close();openEntry(ctx,kind);},{class:'owner-choice'}));surface.body.append(button('Upload files',()=>{surface.close();uploads();},{class:'owner-choice'}));}
async function discard(){if(pendingPublication||lock){notice('First confirm the pending publication from Review & publish.');return;}if(!changes.length||!confirm('Discard all unpublished changes on this device?'))return;undo.push(structuredClone(changes));changes=[];publishKey=null;model=readOwnerModel(snapshot);await persist();refresh();notice('Unpublished changes discarded.');}
async function exit(){if(connection.mode==='github')await connection.call('logout');connection.close();sessionStorage.removeItem('zh-owner-active');location.href=base+'/';}
function refresh(){toolbar?.querySelector('[data-owner-change-count]')?.replaceChildren(`${changes.length} changes`);const undoButton=toolbar?.querySelector('[data-owner-undo]');if(undoButton)undoButton.disabled=!undo.length||lock||Boolean(pendingPublication)||needsRefresh;renderBindings();installInline();renderDashboard();for(const node of document.querySelectorAll('[data-owner-entry]')){const entry=model.entries[node.dataset.ownerKind]?.find(item=>item.slug===node.dataset.ownerSlug);node.dataset.ownerDeleted=String(!entry);if(entry){const heading=node.querySelector('h2,h3');if(heading)heading.textContent=entry.metadata.title;}}}
function dashboardGroup(kind){const section=el('section',{class:'owner-dashboard-section'},el('div',{class:'owner-section-heading'},el('h2',{},kind==='notes'?'Course notes':kind[0].toUpperCase()+kind.slice(1)),button('New '+kind,()=>openEntry(ctx,kind),{class:'owner-primary'}))),list=el('div',{class:'owner-entry-list'});
  model.entries[kind].forEach(entry=>{const drafted=changes.some(change=>change.path===entry.path);list.append(el('article',{class:'owner-entry-row'},el('div',{},el('h3',{},entry.metadata.title),el('p',{class:'owner-muted'},[entry.metadata.status||entry.metadata.category,entry.metadata.date,drafted?'Unpublished changes':null,entry.metadata.featured?'Featured':null].filter(Boolean).join(' · '))),el('div',{class:'owner-row-actions'},button('Edit',()=>openEntry(ctx,kind,entry.slug)),button('Preview',()=>openPreview(ctx,entry.metadata.title,entry.editBody)),button(kind==='notes'?'Notes':'Documents',()=>documents(kind,entry.slug)),button('Files',()=>uploads({kind,slug:entry.slug})),...(kind==='research'?[button('Add update',()=>openLog(ctx,entry.slug))]:[]),button('Delete',()=>deleteEntry(ctx,kind,entry.slug)),el('a',{href:base+`/${kind}/${entry.slug}/`,target:'_blank',rel:'noopener'},'View'))));});section.append(list);return section;
}
function dashboardOverview(){
  const active=effective(),assetBytes=active.files.filter(file=>file.path.startsWith('hub/public/uploads/')).reduce((total,file)=>total+(file.size||0),0);
  const repository=snapshot.repository||{},repoURL=connection.session.repository?.url||snapshot.repoInfo?.url||'https://github.com/Z-hang729/Z-hang-Homepage';
  const summary=el('section',{class:'owner-dashboard-summary','aria-label':'Website overview'});
  const stat=(label,value,detail)=>el('article',{class:'owner-stat'},el('span',{class:'owner-muted'},label),el('strong',{},value),detail?el('small',{class:'owner-muted'},detail):null);
  summary.append(...['research','notes','projects'].map(kind=>stat(kind==='notes'?'Courses':kind[0].toUpperCase()+kind.slice(1),String(model.entries[kind].length),'Including this draft')),
    stat('Uploaded files',formatBytes(assetBytes),'Current website assets'),stat('Repository size',Number.isFinite(repository.sizeBytes)?formatBytes(repository.sizeBytes):'Unavailable',connection.mode==='github'?'Reported by GitHub, including history':'Available after online sign-in'));
  const sha=connection.mode==='github'?snapshot.head:snapshot.repoInfo?.gitHead,matched=dashboardStatus.head===snapshot.head,status=matched?dashboardStatus.result:null,commit=matched?dashboardStatus.commit:null;
  const state=connection.mode!=='github'?'Local development':dashboardStatus.loading?'Checking…':dashboardStatus.error?'Check unavailable':status?.phase==='deployed'?'Deployed':status?.phase==='deploy_failed'?'Deployment failed':status?.phase==='build_failed'?'Build failed':status?.phase?.replaceAll('_',' ')||'Not checked';
  const latest=el('section',{class:'owner-dashboard-publishing','aria-label':'Latest commit and deployment'},el('h2',{},'Publishing status'),
    el('p',{},'Latest commit: ',sha?el('a',{href:`${repoURL}/commit/${sha}`,target:'_blank',rel:'noopener'},sha.slice(0,7)):el('span',{},'No commit yet'),commit?.date?` · ${new Date(commit.date).toLocaleString()}`:''),
    el('p',{'data-owner-pages-status':'',role:'status'},`Pages: ${state}`,status?` · Build: ${status.build?.state||'pending'} · Deployment: ${status.deployment?.state||'pending'}`:''),
    status?.deployment?.url?el('a',{href:status.deployment.url,target:'_blank',rel:'noopener'},'Open deployed website'):null,
    dashboardStatus.error?el('p',{class:'owner-warning'},dashboardStatus.error):null,
    el('div',{class:'owner-row-actions'},el('a',{href:repoURL,target:'_blank',rel:'noopener'},'Open repository'),el('a',{href:repoURL+'/actions',target:'_blank',rel:'noopener'},'View Actions'),
      button('Refresh publishing status',safeAction(loadDashboardStatus),{disabled:connection.mode!=='github'||dashboardStatus.loading||lock})));
  return [summary,latest];
}
async function loadDashboardStatus(){
  if(connection.mode!=='github'||dashboardStatus.loading||lock)return;
  const head=snapshot.head;dashboardStatus={head,loading:true,result:null,commit:null,error:null};renderDashboard();
  try{const history=await connection.call('history');const result=await connection.call('status',{sha:head});dashboardStatus={head,loading:false,result,commit:history.commits?.find(commit=>commit.sha===head)||null,error:null};}
  catch(error){dashboardStatus={head,loading:false,result:null,commit:null,error:error.message};}
  renderDashboard();
}
function renderDashboard(){const workspace=document.querySelector('[data-owner-workspace]');if(!workspace)return;workspace.hidden=false;document.querySelector('[data-owner-dashboard] > [data-owner-login]')?.setAttribute('hidden','');const session=connection.session;
  const heading=el('header',{class:'owner-dashboard-header'},el('div',{},el('p',{class:'eyebrow'},connection.mode==='github'?'SIGNED IN AS '+session.owner.login:'LOCAL DEVELOPMENT'),el('h1',{},'Owner workspace'),el('p',{class:'owner-muted'},connection.mode==='github'?`${session.repository.owner}/${session.repository.name} · ${session.repository.branch}`:'Changes save to this local website. Production editing requires the configured authentication service.')),el('a',{href:base+'/',class:'button'},'Edit homepage'));
  const shortcuts=el('div',{class:'owner-dashboard-shortcuts'},button('Profile',()=>openProfile(ctx)),button('Homepage layout',()=>openHomepage(ctx)),button('Navigation',()=>openNavigation(ctx)),button('File manager',files),button('Upload folder',()=>uploads()),button('History & deployment',()=>openHistory()));
  const draft=el('section',{class:'owner-draft-panel'},el('div',{},el('h2',{},changes.length?`${changes.length} unpublished file changes`:'Your draft is clear'),el('p',{class:'owner-muted'},changes.length?'Saved on this device. Review the whole batch before publishing.':'Open a page to edit in place, or add content below.')),button(connection.mode==='github'?'Review & publish':'Review & save locally',openReview,{class:'owner-primary',disabled:!changes.length}));
  const updates=el('section',{class:'owner-dashboard-section'},el('h2',{},'Research updates'),...model.logs.map(log=>el('div',{class:'owner-log-row'},el('div',{},el('strong',{},log.metadata.title),el('p',{class:'owner-muted'},`${log.metadata.date} · ${log.metadata.project}`)),button('Edit update',()=>openLog(ctx,log.metadata.project,log.path)))));
  const receipt=confirmedPublication?el('section',{class:'owner-saved-receipt','data-owner-last-saved':confirmedPublication.phase,role:'status'},el('strong',{},confirmedPublication.phase==='saved-local'?'Saved locally':'Committed to GitHub'),el('p',{class:'owner-muted'},confirmedPublication.phase==='saved-local'?'Your last batch was saved successfully to this local website.':'Your content commit was saved. Check its build and deployment separately.'),confirmedPublication.commit?el('a',{href:confirmedPublication.commit.url,target:'_blank',rel:'noopener'},'View commit '+confirmedPublication.commit.sha.slice(0,7)):null):null;
  workspace.replaceChildren(heading,...dashboardOverview(),shortcuts,...(receipt?[receipt]:[]),draft,...['research','notes','projects'].map(dashboardGroup),updates);
}
function openReview(){const surface=modal(connection.mode==='github'?'Review & publish':'Review & save locally',connection.mode==='github'?'The complete batch becomes one GitHub commit. The site goes live after its build succeeds.':'Save the complete batch to the local website. This does not publish to GitHub.');if(!changes.length){surface.body.append(el('p',{},'There are no unpublished changes.'));return;}
  const list=el('div',{class:'owner-review-list'});summarizeChanges(changes,snapshot).forEach(item=>{const change=changes.find(c=>c.path===item.path),old=snapshot.files.find(file=>file.path===item.path),details=el('details',{class:'owner-review-file'},el('summary',{},el('span',{class:'owner-change-action'},item.action),item.path.replace(/^hub\//,''),el('small',{},formatBytes(item.bytes))));
    if(change.encoding==='utf8'||old?.encoding==='utf8')details.append(el('div',{class:'owner-diff'},el('div',{},el('strong',{},'Before'),el('pre',{},old?.content||'(new file)')),el('div',{},el('strong',{},'After'),el('pre',{},change.action==='delete'?'(deleted)':change.content))));else details.append(el('p',{class:'owner-muted'},'Binary attachment: '+formatBytes(item.bytes)));list.append(details);});surface.body.append(list);const message=inputField('Commit message',pendingPublication?.message||suggestCommitMessage(changes,snapshot));message.input.disabled=Boolean(pendingPublication);surface.body.append(message.node);
  formAction(surface,connection.mode==='github'?'Confirm publish':'Confirm local save',async()=>{if(lock)throw new Error('A publish is already running.');const retrying=Boolean(pendingPublication);lock=true;surface.dialog.querySelectorAll('button').forEach(node=>node.disabled=true);surface.status.textContent='Validating and saving the complete batch…';try{
      validateDraftChanges(snapshot,changes);publishKey ||=crypto.randomUUID();const envelope=pendingPublication||{expectedHead:snapshot.head,idempotencyKey:publishKey,message:message.input.value.trim()||suggestCommitMessage(changes,snapshot),changes:structuredClone(changes)};
      const {result,warnings}=await publishBatch({transport:connection,envelope,remember:async value=>{pendingPublication=value;await persist();},acknowledge:async value=>{confirmedPublication=value;changes=[];undo=[];publishKey=null;pendingPublication=null;needsRefresh=true;await persist();},refresh:async()=>{snapshot=await connection.call('snapshot');model=readOwnerModel(snapshot);needsRefresh=false;await persist();}});refresh();surface.close();
      warnings.push(...await cleanupCommittedStorage(result));
      if(result.phase==='saved-local'){notice('Saved locally. GitHub has not been published.');const local=modal('Saved locally','The complete batch was written successfully.');local.body.append(el('p',{},'Reload to see the rebuilt page.'),...warnings.map(text=>el('p',{class:'owner-warning'},text)));local.actions.append(button('Reload page',()=>location.reload(),{class:'owner-primary'}));}else{notice('Committed to GitHub. Checking the website build…');const deployed=await showDeployment(result.commit);deployed.body.append(...warnings.map(text=>el('p',{class:'owner-warning'},text)));}
    }catch(error){const recovery=classifyPublicationError(error,{retrying});if(recovery.clearPending){pendingPublication=null;publishKey=null;await persist().catch(()=>{});}surface.status.textContent=error.message+' '+recovery.guidance;surface.status.dataset.error='true';surface.actions.querySelector('[data-owner-review-latest]')?.remove();if(recovery.allowRebase)surface.actions.append(button('Check latest version',safeAction(rebase),{'data-owner-review-latest':''}));error.message=surface.status.textContent;throw error;}finally{lock=false;surface.dialog.querySelectorAll('button').forEach(node=>node.disabled=false);refresh();}});
}
async function applyRebase(latest,next){if(lock)throw new Error('Wait for the current publish to finish.');if(pendingPublication)throw new Error('Confirm the original publication before merging this draft.');if(needsRefresh)throw new Error('Your save succeeded. Reload the workspace before merging this draft.');validateDraftChanges(latest,next);const candidate=readOwnerModel(applyDraftToSnapshot(latest,next));await saveDraft(draftKey,{head:latest.head,baseline:latest,changes:next,updatedAt:new Date().toISOString()});snapshot=latest;changes=next;model=candidate;publishKey=null;pendingPublication=null;confirmedPublication=null;undo=[];refresh();}
async function rebase(){if(pendingPublication){notice('The previous publication needs confirmation. Keep its original request and retry it before reviewing another version.');return false;}const latest=await connection.call('snapshot'),files=new Map(latest.files.map(file=>[file.path,file])),conflicts=changes.filter(change=>(files.get(change.path)?.sha??null)!==change.expectedSha);if(conflicts.length){const surface=modal('Review draft conflicts','Choose how to resolve each changed file. Nothing is published from this window.');const decisions=new Map();for(const change of conflicts){const current=files.get(change.path),choice=el('select',{},el('option',{value:''},'Choose a resolution'),el('option',{value:'latest'},'Use the latest repository file'),el('option',{value:'draft'},'Keep my draft after review'));surface.body.append(el('section',{class:'owner-review-file'},el('h3',{},change.path),el('div',{class:'owner-diff'},el('div',{},el('strong',{},'Latest repository version'),el('pre',{},current?.encoding==='base64'?'Binary attachment':current?.content||'(deleted)')),el('div',{},el('strong',{},'Your draft'),el('pre',{},change.action==='delete'?'(delete)':change.encoding==='base64'?'Binary attachment':change.content))),choice));decisions.set(change.path,choice);}surface.actions.append(button('Export draft',exportDraft));formAction(surface,'Apply reviewed resolutions',async()=>{if([...decisions.values()].some(input=>!input.value))throw new Error('Choose a resolution for every conflicting file.');const next=changes.filter(change=>decisions.get(change.path)?.value!=='latest').map(change=>({...change,expectedSha:files.get(change.path)?.sha??null})).filter(change=>change.action!=='delete'||files.has(change.path));await applyRebase(latest,next);surface.close();notice('Reviewed resolutions saved. Open Review & publish to publish the batch.');});notice('Conflicting changes need review; nothing was overwritten.');return false;}await applyRebase(latest,changes);notice('Latest repository version loaded. Your edits do not conflict; review and publish again.');return true;}
function exportDraft(){const blob=new Blob([JSON.stringify({head:snapshot.head,changes},null,2)],{type:'application/json'}),link=el('a',{href:URL.createObjectURL(blob),download:'website-draft.json'});link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
async function showDeployment(commit){const surface=modal('GitHub commit saved','The website build and deployment are separate steps.'),output=el('p',{role:'status'});surface.body.append(el('a',{href:commit.url,target:'_blank',rel:'noopener'},'View commit '+commit.sha.slice(0,7)),output);const check=async()=>{const status=await connection.call('status',{sha:commit.sha});output.replaceChildren(...[el('span',{},`Build: ${status.build?.state||'pending'} · Deployment: ${status.deployment?.state||'pending'}`),status.build?.runUrl?el('a',{href:status.build.runUrl,target:'_blank',rel:'noopener'},'Open build'):null,status.deployment?.url?el('a',{href:status.deployment.url,target:'_blank',rel:'noopener'},'Open website'):null].filter(Boolean));if(status.phase==='deployed'||status.deployment?.state==='success')notice('The website is live with this commit.');else if(status.build?.state==='failure')notice('The commit was saved, but the website build failed. Open the build report.');return status;};surface.actions.append(button('Check again',safeAction(check)));try{await check();}catch(error){output.textContent='The commit was saved. Status check failed: '+error.message;}return surface;}
async function openHistory(){const surface=modal('History & deployment');try{const history=await connection.call('history');if(connection.mode!=='github'){surface.body.append(el('p',{},'Local saves are independent of GitHub commits.'),el('pre',{},JSON.stringify(history,null,2)));return;}for(const commit of history.commits||[])surface.body.append(el('div',{class:'owner-history-row'},el('a',{href:commit.url,target:'_blank',rel:'noopener'},commit.message),el('small',{},commit.date),button('Deployment',()=>showDeployment(commit))));}catch(error){surface.status.textContent=error.message;}}
function formatBytes(bytes){return bytes>=1048576?(bytes/1048576).toFixed(1)+' MiB':bytes>=1024?(bytes/1024).toFixed(1)+' KiB':bytes+' B';}
async function activate(transport){connection=transport;snapshot=await connection.call('snapshot');model=readOwnerModel(snapshot);draftKey=connection.mode==='github'?`github:${connection.session.repository.owner}/${connection.session.repository.name}:${connection.session.repository.branch}`:'local:'+location.origin+base;
  const recovered=await readDraft(draftKey);confirmedPublication=recovered?.confirmedPublication||null;let recoveredSave=null,recoveryNotice='';
  if(recovered?.pendingPublication){changes=recovered.changes||[];snapshot=recovered.baseline||snapshot;pendingPublication=recovered.pendingPublication;publishKey=pendingPublication.idempotencyKey;
    try{const outcome=await publishBatch({transport:connection,envelope:pendingPublication,remember:async()=>{},acknowledge:async result=>{confirmedPublication=result;recoveredSave=result;changes=[];undo=[];publishKey=null;pendingPublication=null;needsRefresh=true;await persist();},refresh:async()=>{snapshot=await connection.call('snapshot');needsRefresh=false;await persist();}});recoveredSave=outcome.result;notice('The previous save was confirmed.');}
    catch(error){const recovery=classifyPublicationError(error,{retrying:true});if(recovery.clearPending){pendingPublication=null;publishKey=null;await persist().catch(()=>{});}recoveryNotice=error.message+' '+recovery.guidance;notice(recoveryNotice);}
  }else if(recovered?.changes?.length){changes=recovered.changes;publishKey=recovered.publishKey||null;}
  if(changes.length){if(!pendingPublication&&((recovered?.head||snapshot.head)!==snapshot.head||recovered?.pendingPublication)){const latest=await connection.call('snapshot'),files=new Map(latest.files.map(file=>[file.path,file]));if(changes.some(change=>(files.get(change.path)?.sha??null)!==change.expectedSha)){snapshot=recovered?.baseline||{...latest,head:recovered.head};const surface=modal('Saved draft needs review','Content changed since this draft. Nothing will be overwritten.');surface.actions.append(button('Review conflicts',safeAction(async()=>{surface.close();await rebase();})),button('Export draft',exportDraft));}else snapshot=latest;}model=readOwnerModel(effective());notice(pendingPublication?recoveryNotice||'A previous publish needs confirmation. Retry it from Review & publish.':'Your unpublished draft has been restored.');}
  else model=readOwnerModel(snapshot);
  sessionStorage.setItem('zh-owner-active',connection.mode);createToolbar();refresh();await persist();window.addEventListener('beforeunload',event=>{if(changes.length){event.preventDefault();event.returnValue='';}});
  const cleanupWarnings=await cleanupCommittedStorage(confirmedPublication);
  if(recoveredSave?.phase==='saved-local'){const surface=modal('Saved locally','Your previous save was confirmed after the page refreshed.');surface.body.append(el('p',{},'The complete batch was saved once. GitHub has not been published.'));surface.actions.append(button('Continue editing',()=>surface.close(),{class:'owner-primary'}));}
  else if(recoveredSave?.commit)await showDeployment(recoveredSave.commit);
  else if(document.querySelector('[data-owner-workspace]'))await loadDashboardStatus();
  return cleanupWarnings;
}
export async function startOwner(){if(editing)return;editing=true;const localButton=document.querySelector('[data-owner-local-login]'),remoteButton=document.querySelector('[data-owner-sign-in]');async function signIn(local){const action=local?localButton:remoteButton;if(action)action.disabled=true;try{notice(local?'Opening the local editor…':'Complete sign-in in the secure connection window.');const warnings=await activate(local?await connectLocal():await connectRemote(backend()));if(warnings.length)notice(warnings.join(' '));else if(!pendingPublication&&!needsRefresh)notice(connection.mode==='github'?'Owner identity verified. Changes stay in your draft until published.':'Local editing is active. Saves apply only to this local website.');}catch(error){notice(error.message);}finally{if(action)action.disabled=false;}}localButton?.addEventListener('click',()=>signIn(true));remoteButton?.addEventListener('click',()=>signIn(false));if(localButton)localButton.disabled=!import.meta.env.DEV;if(remoteButton)remoteButton.disabled=!backend();document.documentElement.dataset.ownerReady='true';const status=document.querySelector('[data-owner-login-status]');if(status)status.textContent=backend()?'Ready to sign in.':import.meta.env.DEV?'Local editor ready.':'Online sign-in is awaiting configuration.';const resume=sessionStorage.getItem('zh-owner-active');if(resume==='local-development'&&import.meta.env.DEV)await signIn(true);else if(resume==='github'&&backend())await signIn(false);}
