import {el,button,inputField,selectField,modal,formAction,structuredRows} from './dom.js';
import {deriveCV,normalizeCV,CV_SECTION_TITLES} from '../lib/academic-cv.mjs';
import {knowledgeNodesFromFiles} from '../lib/knowledge.mjs';
import {cvChanges} from '../lib/academic-model.mjs';

/** Dedicated CV fields never write homepage/profile YAML. */
export function openCV(ctx){
  const model=ctx.model(),snapshot=ctx.snapshot(),file=snapshot.files.find(item=>/(?:^|\/)src\/data\/cv\.json$/.test(item.path));
  const recordSource=file?JSON.parse(file.content):{},original=normalizeCV(recordSource),nodes=knowledgeNodesFromFiles(snapshot.files),resolved=deriveCV(model.profile,recordSource,nodes);
  const surface=modal('Academic CV','Edit CV-only overrides, select existing work, and arrange sections. The homepage profile stays unchanged. Empty sections are hidden.');
  const profileInputs={},profileGrid=el('div',{class:'owner-form-grid'});
  for(const [key,label]of [['displayName','Display name'],['role','Role'],['university','University'],['degree','Primary degree'],['secondDegree','Second degree'],['bio','Profile'],['email','Public email'],['github','GitHub URL'],['location','Location']]){const field=inputField(label,resolved.profile[key]||'',{multiline:key==='bio'});profileInputs[key]=field.input;profileGrid.append(field.node);}
  surface.body.append(el('h3',{},'CV profile'),profileGrid);
  const inherit=el('input',{type:'checkbox',checked:Object.keys(original.profile).length===0});surface.body.append(el('label',{class:'owner-check'},inherit,'Use current homepage profile for the CV profile fields'));
  function repeater(key,label,fields){const rows=structuredRows(label,resolved[key].map(value=>typeof value==='string'?{title:value}:value),fields);surface.body.append(rows.node);return rows;}
  const education=repeater('education','Education',[{key:'start',label:'Start'},{key:'end',label:'End'},{key:'institution',label:'Institution'},{key:'description',label:'Description',multiline:true}]);
  const experience=repeater('researchExperience','Research experience',[{key:'title',label:'Role / title'},{key:'institution',label:'Institution'},{key:'start',label:'Start'},{key:'end',label:'End'},{key:'description',label:'Description',multiline:true},{key:'url',label:'Public URL (optional)'}]);
  const lists={};for(const [key,label]of [['researchInterests','Research interests, one per line'],['skills','Skills, one per line']]){lists[key]=inputField(label,resolved[key].join('\n'),{multiline:true});surface.body.append(lists[key].node);}
  const selected={};
  function selectExisting(key,label,type){const choices=nodes.filter(node=>node.type===type&&node.metadata?.demo!==true&&(node.visibility||'public')==='public'&&(node.metadata?.publicationStatus||node.publicationStatus)==='published'),list=el('fieldset',{class:'owner-repeater'},el('legend',{},label)),rows=[];selected[key]=()=>rows.map(row=>({id:row.select.input.value,description:row.description.input.value.trim()}));
    function add(value={}){const row=el('div',{class:'owner-structured-row'}),select=selectField('Existing item',value.id||choices[0]?.id||'',[{value:'',label:'Choose existing public content'},...choices.map(node=>({value:node.id,label:`${node.title} (${node.id})`}))]),description=inputField('CV description (optional)',value.description||'',{multiline:true}),record={row,select,description};rows.push(record);row.append(select.node,description.node,button('Move up',()=>{const at=rows.indexOf(record);if(at>0){rows.splice(at,1);rows.splice(at-1,0,record);list.insertBefore(row,rows[at].row);}}),button('Move down',()=>{const at=rows.indexOf(record);if(at<rows.length-1){rows.splice(at,1);rows.splice(at+1,0,record);list.insertBefore(rows[at].row,row);}}),button('Remove from CV',()=>{rows.splice(rows.indexOf(record),1);row.remove();}));list.append(row);}
    for(const value of original[key])add(value);list.append(button('Select existing item',()=>add(),{disabled:!choices.length}));if(!choices.length)list.append(el('p',{class:'owner-muted'},'No public non-demo content is available yet.'));surface.body.append(list);
  }
  selectExisting('selectedResearch','Selected research','research');selectExisting('selectedProjects','Selected projects','project');
  const publicationList=el('fieldset',{class:'owner-repeater'},el('legend',{},'Publications')),publicationRows=[];
  const referenceChoices=nodes.filter(node=>node.type==='reference'&&(node.visibility||'public')==='public'&&node.metadata?.demo!==true&&(node.metadata?.publicationStatus||node.publicationStatus)==='published');
  function addPublication(value={}){const row=el('div',{class:'owner-structured-row'}),reference=selectField('Existing reference (optional)',value.referenceId||'',[{value:'',label:'Manually authored publication'},...referenceChoices.map(node=>({value:node.id,label:node.title}))]),title=inputField('Title (for a manual publication)',value.title||''),authors=inputField('Authors, separated by semicolons',(value.authors||[]).join('; ')),year=inputField('Year',value.year||''),url=inputField('Public URL',value.url||''),description=inputField('CV description',value.description||'',{multiline:true}),confirmed=el('input',{type:'checkbox',checked:value.ownerConfirmed===true}),record={row,reference,title,authors,year,url,description,confirmed};publicationRows.push(record);row.append(reference.node,title.node,authors.node,year.node,url.node,description.node,el('label',{class:'owner-check'},confirmed,'I confirm that I am an author of this publication and that it belongs in my CV.'),button('Remove publication',()=>{publicationRows.splice(publicationRows.indexOf(record),1);row.remove();}));publicationList.append(row);}
  (recordSource.publications===undefined?resolved.publications.map(item=>({...item,ownerConfirmed:true})):original.publications).forEach(addPublication);publicationList.append(button('Add publication',()=>addPublication()));surface.body.append(publicationList,el('p',{class:'owner-muted'},'Bibliography entries are never added to Publications automatically.'));
  const extras={};for(const [key,label]of [['presentations','Presentations'],['awards','Honors & awards'],['software','Software'],['teaching','Teaching'],['service','Academic service']])extras[key]=repeater(key,label,[{key:'title',label:'Title'},{key:'institution',label:'Institution / venue'},{key:'date',label:'Date / period'},{key:'description',label:'Description',multiline:true},{key:'url',label:'Public URL (optional)'}]);
  const links=repeater('links','Public links',[{key:'title',label:'Label'},{key:'url',label:'URL'}]);
  const sections=el('fieldset',{class:'owner-repeater'},el('legend',{},'Section order and visibility')),sectionRows=[];
  for(const section of resolved.sections){const row=el('div',{class:'owner-order-row'}),visible=el('input',{type:'checkbox',checked:section.visible}),record={row,id:section.id,visible};sectionRows.push(record);row.append(el('label',{class:'owner-check'},visible,CV_SECTION_TITLES[section.id]),button('Move up',()=>{const previous=row.previousElementSibling;if(previous&&previous.tagName!=='LEGEND')sections.insertBefore(row,previous);}),button('Move down',()=>{const next=row.nextElementSibling;if(next)sections.insertBefore(next,row);}));sections.append(row);}surface.body.append(sections);
  surface.actions.append(button('Reset CV profile overrides',()=>{inherit.checked=true;for(const [key,input]of Object.entries(profileInputs))input.value=model.profile[key]||'';}));
  formAction(surface,'Save CV to draft',async()=>{const record={schemaVersion:1,profile:inherit.checked?{}:Object.fromEntries(Object.entries(profileInputs).map(([key,input])=>[key,input.value.trim()])),education:education.value().filter(row=>row.institution),researchExperience:experience.value().filter(row=>row.title||row.institution),selectedResearch:selected.selectedResearch().filter(row=>row.id),selectedProjects:selected.selectedProjects().filter(row=>row.id),publications:publicationRows.map(row=>({...row.reference.input.value?{referenceId:row.reference.input.value}:{title:row.title.input.value.trim(),authors:row.authors.input.value.split(';').map(value=>value.trim()).filter(Boolean),year:row.year.input.value.trim(),url:row.url.input.value.trim()},description:row.description.input.value.trim(),ownerConfirmed:row.confirmed.checked})),links:links.value().filter(row=>row.title&&row.url),sections:[...sections.children].filter(row=>row.tagName!=='LEGEND').map((row,order)=>{const record=sectionRows.find(item=>item.row===row);return {id:record.id,visible:record.visible.checked,order};})};for(const key of Object.keys(lists))record[key]=lists[key].input.value.split('\n').map(value=>value.trim()).filter(Boolean);for(const key of Object.keys(extras))record[key]=extras[key].value().filter(row=>row.title);await ctx.stage(cvChanges(ctx.snapshot(),record));surface.close();});
  return surface;
}
