import {el,button,inputField,selectField,modal,formAction} from './dom.js';
import {readFileRecords,fileGroup} from '../lib/files.mjs';
import {normalizeFigure,ACADEMIC_RELATIONS} from '../lib/figures.mjs';
import {academicRecordChanges,deleteAcademicRecordChanges} from '../lib/academic-model.mjs';
import {knowledgeNodesFromFiles} from '../lib/knowledge.mjs';
export function readAcademicDraftRecords(ctx,kind){const files=ctx.snapshot().files,entries=files instanceof Map?[...files.values()]:files;return entries.filter(file=>file.path.startsWith(`hub/src/data/${kind}/`)&&file.path.endsWith('.json')&&typeof file.content==='string').map(file=>JSON.parse(file.content));}
export function academicChooser(title,selected,choices,{multiple=true}={}){
 const values=new Set((selected||[]).filter(Boolean)),root=el('fieldset',{class:'owner-repeater'},el('legend',{},title)),query=inputField('Search '+title.toLowerCase()),list=el('div',{style:'max-height:240px;overflow:auto;display:grid;gap:.5rem'}),rows=[];
 const known=new Set(choices.map(choice=>choice.id));for(const choice of [...choices,...[...values].filter(id=>!known.has(id)).map(id=>({id,title:'Unavailable reference: '+id}))]){const input=el('input',{type:multiple?'checkbox':'radio',name:multiple?'':title,value:choice.id,checked:values.has(choice.id)}),row=el('label',{class:'owner-check',style:'overflow-wrap:anywhere'},input,el('span',{},choice.title,choice.detail&&el('small',{class:'owner-muted',style:'display:block'},choice.detail)));input.addEventListener('change',()=>{if(!multiple)values.clear();if(input.checked)values.add(choice.id);else values.delete(choice.id);});rows.push({node:row,text:`${choice.title} ${choice.detail||''} ${choice.id}`.toLocaleLowerCase()});list.append(row);}
 if(!choices.length)list.append(el('p',{class:'owner-muted'},'No matching records are available. Add them to the existing Library or content editor first.'));
 query.input.addEventListener('input',()=>rows.forEach(row=>row.node.hidden=!row.text.includes(query.input.value.toLocaleLowerCase())));root.append(query.node,list);return {node:root,value:()=>[...values]};
}
export function academicRelationChoices(ctx,type){return knowledgeNodesFromFiles(ctx.snapshot().files).filter(node=>node.type===type).map(node=>({id:node.id,title:node.title,detail:node.id}));}
export function academicMetadataControls(surface,original,{kind}={}){
 const controls={},grid=el('div',{class:'owner-form-grid'});
 for(const [key,label,options]of [['id',`Stable ${kind}:slug ID`],['title','Title'],['date','Date',{type:'date'}],['updated','Updated',{type:'date'}],['description','Description (Markdown)',{multiline:true}],['tags','Tags, comma separated'],['authors','Authors, one per line',{multiline:true,rows:2}],['source','Source / provenance'],['license','License (Unknown if unspecified)']]){const value=key==='tags'?(original.tags||[]).join(', '):key==='authors'?(original.authors||[]).join('\n'):original[key]||'',field=inputField(label,value,options||{});field.input.name=key;if(key==='id'&&original.id)field.input.disabled=true;controls[key]=field.input;grid.append(field.node);}
 const visibility=selectField('Visibility',original.visibility||'unlisted',['unlisted','public']),publication=selectField('Publication',original.publicationStatus||'draft',['draft','published','archived']);controls.visibility=visibility.input;controls.publicationStatus=publication.input;grid.append(visibility.node,publication.node);surface.body.append(grid,el('p',{class:'owner-muted'},'Drafts stay in this device’s Owner draft. Public static pages are generated only for explicitly published, public records. Unlisted records are not confidential and belong to a public repository.'));
 const relations={};for(const [key,type]of Object.entries(ACADEMIC_RELATIONS)){if(key==='relatedFiles')continue;const choices=academicRelationChoices(surface.ctx,type);if(!choices.length&&!(original[key]||[]).length)continue;const chooser=academicChooser(key.replace(/^related/,'Related '),original[key]||[],choices);relations[key]=chooser;surface.body.append(chooser.node);}
 return {value:()=>({...Object.fromEntries(Object.entries(controls).map(([key,input])=>[key,input.value.trim()])),tags:[...new Set(controls.tags.value.split(',').map(value=>value.trim()).filter(Boolean))],authors:controls.authors.value.split('\n').map(value=>value.trim()).filter(Boolean),...Object.fromEntries(Object.entries(relations).map(([key,chooser])=>[key,chooser.value()]))})};
}
export function openFigure(ctx,{id=null,record=null}={}){
 const files=readFileRecords(ctx.snapshot()),original=record||(id?readAcademicDraftRecords(ctx,'figures').find(value=>value.id===id):null);
 if(id&&!original){ctx.notice('This figure is no longer in the draft.');return;}
 const initial=original||{title:'',date:new Date().toISOString().slice(0,10),updated:new Date().toISOString().slice(0,10),source:'Unspecified',license:'Unknown'},surface=modal(original?'Edit scientific figure':'Add scientific figure','Select an existing Library original. Removing a figure only removes gallery metadata; it never deletes the original file.');surface.ctx=ctx;surface.dialog.dataset.figureEditor='';
 const common=academicMetadataControls(surface,initial,{kind:'figure'}),caption=inputField('Scientific caption (Markdown)',initial.caption||'',{multiline:true,rows:5}),alt=inputField('Image alt text',initial.altText||'',{multiline:true,rows:2}),category=inputField('Category',initial.category||''),transform=inputField('Display transformation (if any)',initial.displayTransformation||'',{multiline:true,rows:3}),featured=el('input',{type:'checkbox',checked:initial.featured});
 const choices=files.filter(file=>!file.isFolderBundle&&!file.isDerivative&&(fileGroup(file)==='images'||file.previewType==='fits'||file.previewType==='pdf')).map(file=>({id:file.id,title:file.displayName,detail:file.originalName+' · '+file.visibility})),originalFile=academicChooser('Original scientific image',[initial.fileId],choices,{multiple:false}),thumbnails=files.filter(file=>file.previewType==='image').map(file=>({id:file.id,title:file.displayName,detail:file.originalName})),thumbnail=selectField('Thumbnail (optional)',initial.thumbnailId||'',[{value:'',label:'Use original when safe'},...thumbnails.map(file=>({value:file.id,label:file.title}))]);
 surface.body.append(caption.node,alt.node,category.node,transform.node,el('label',{class:'owner-check'},featured,'Featured in gallery'),originalFile.node,thumbnail.node,el('p',{class:'owner-muted'},'Preview transformations describe presentation only; they do not modify the original scientific pixels. Unknown source, author or license remains unspecified.'));
 formAction(surface,'Save figure to draft',async()=>{const selected=originalFile.value()[0];const next=normalizeFigure({...initial,...common.value(),fileId:selected,thumbnailId:thumbnail.input.value||null,caption:caption.input.value.trim(),altText:alt.input.value.trim(),category:category.input.value.trim()||'Unspecified',displayTransformation:transform.input.value.trim(),featured:featured.checked},{files});await ctx.stage(academicRecordChanges(ctx.snapshot(),{kind:'figures',record:next,originalId:original?.id}));surface.close();});
 if(original)surface.actions.prepend(button('Remove from gallery',()=>removeFigure(ctx,original,{onRemoved:()=>surface.close()})));
 return surface;
}
export function removeFigure(ctx,record,{onRemoved}={}){const surface=modal('Remove figure from gallery','Only the figure metadata will be removed. Its Library original and thumbnail remain intact. Existing content references must be removed before deletion.');surface.body.append(el('p',{},record.title),el('code',{},record.id));const confirmation=inputField('Type the complete stable figure ID');surface.body.append(confirmation.node);formAction(surface,'Remove gallery metadata',async()=>{await ctx.stage(deleteAcademicRecordChanges(ctx.snapshot(),{kind:'figures',id:record.id,confirmation:confirmation.input.value}));surface.close();onRemoved?.();});return surface;}
export function openFigures(ctx){const surface=modal('Scientific figures','Manage metadata and reuse existing Library originals.'),list=el('div',{class:'owner-entry-list'});surface.dialog.dataset.figuresManager='';surface.body.append(button('Add figure',()=>{surface.close();openFigure(ctx);}),list);for(const record of readAcademicDraftRecords(ctx,'figures'))list.append(el('article',{class:'owner-entry-row'},el('div',{},el('h3',{},record.title),el('p',{class:'owner-muted'},`${record.date} · ${record.publicationStatus} · ${record.visibility}`)),button('Edit',()=>{surface.close();openFigure(ctx,{id:record.id});}),button('Remove',()=>removeFigure(ctx,record,{onRemoved:()=>{surface.close();openFigures(ctx);}}))));if(!list.children.length)list.append(el('p',{class:'owner-muted'},'No scientific figures yet. Add a real figure when it is ready.'));return surface;}
export function installFigureControls(ctx){for(const node of document.querySelectorAll('[data-owner-figure-id],[data-owner-figures]')){if(node.dataset.ownerFiguresInstalled)continue;node.dataset.ownerFiguresInstalled='true';node.prepend(el('div',{class:'owner-card-controls'},button(node.dataset.ownerFigureId?'Edit figure':'Manage figures',()=>node.dataset.ownerFigureId?openFigure(ctx,{id:node.dataset.ownerFigureId}):openFigures(ctx))));}}
