/** CV-only overrides. The homepage profile remains the authority for inherited fields. */
export const CV_SECTION_IDS = ['profile','education','researchInterests','researchExperience','selectedResearch','selectedProjects','publications','presentations','awards','skills','software','teaching','service','links'];
export const CV_SECTION_TITLES = {profile:'Profile',education:'Education',researchInterests:'Research interests',researchExperience:'Research experience',selectedResearch:'Selected research',selectedProjects:'Selected projects',publications:'Publications',presentations:'Presentations',awards:'Honors & awards',skills:'Skills',software:'Software',teaching:'Teaching',service:'Academic service',links:'Links'};
const profileKeys = ['displayName','role','university','degree','secondDegree','bio','email','github','location'];
const textArrays = ['researchInterests','skills'];
const entryArrays = ['education','researchExperience','presentations','awards','software','teaching','service','links'];
const object = value => value && typeof value==='object' && !Array.isArray(value);
function text(value,label,{required=false}={}) { if(typeof value!=='string'||value.length>20000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value)||(required&&!value.trim()))throw new Error(`${label} must be ${required?'nonempty ':''}text.`); return value; }
function safeURL(value,label) { text(value,label); if(!value)return; if(value!==value.trim()||/[\u0000-\u0020\\]/.test(value)||value.startsWith('//'))throw new Error(`${label} must be a safe URL.`); let decoded;try{decoded=decodeURIComponent(value);}catch{throw new Error(`${label} has invalid URL escaping.`);}if(/[\u0000-\u0020\\]/.test(decoded)||/(?:^|\/)\.\.(?:\/|$)/.test(decoded)||/^(?:javascript|data|vbscript):/i.test(decoded))throw new Error(`${label} must be a safe URL.`); if(value.startsWith('/')||value.startsWith('#'))return;let url;try{url=new URL(value);}catch{throw new Error(`${label} must be an http(s), mailto, or root-relative URL.`);}if(!['https:','http:','mailto:'].includes(url.protocol)||url.username||url.password)throw new Error(`${label} must be a safe URL.`); }
function list(value,label) {if(!Array.isArray(value)||value.length>500)throw new Error(`${label} must be a list with at most 500 items.`);return value;}
function entry(value,label) { if(typeof value==='string'){text(value,label,{required:true});return;}if(!object(value))throw new Error(`${label} must be an object.`);for(const [key,item]of Object.entries(value)){if(key==='authors'){list(item,`${label}.authors`).forEach(author=>text(author,`${label}.authors`));}else if(key==='ownerConfirmed'){if(typeof item!=='boolean')throw new Error('ownerConfirmed must be a boolean.');}else {text(item,`${label}.${key}`);if(['url','href'].includes(key))safeURL(item,`${label}.${key}`);}} }
function selections(value,type,label) {const ids=new Set();for(const item of list(value,label)){if(!object(item)||typeof item.id!=='string'||!new RegExp(`^${type}:[^\\s<>\\\\?#]+$`).test(item.id)||item.id.split(':').length!==2)throw new Error(`${label} must refer to an existing ${type} stable ID.`);if(ids.has(item.id))throw new Error(`Duplicate CV selection: ${item.id}`);ids.add(item.id);if(item.description!==undefined)text(item.description,`${label}.description`);}}
export function validateCV(record) {
  if(!object(record))throw new Error('CV data must be an object.');
  if(record.schemaVersion!==undefined&&record.schemaVersion!==1)throw new Error('Unsupported CV schema version.');
  if(record.profile!==undefined){if(!object(record.profile))throw new Error('CV profile must be an object.');for(const [key,value]of Object.entries(record.profile)){if(!profileKeys.includes(key))throw new Error(`Unknown CV profile field: ${key}`);text(value,`profile.${key}`);if(key==='github')safeURL(value,`profile.${key}`);if(key==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new Error('Use a valid public email address.');}}
  for(const key of textArrays)if(record[key]!==undefined)list(record[key],key).forEach(value=>text(value,key,{required:true}));
  for(const key of entryArrays)if(record[key]!==undefined)list(record[key],key).forEach(value=>entry(value,key));
  for(const [key,type]of [['selectedResearch','research'],['selectedProjects','project']])if(record[key]!==undefined)selections(record[key],type,key);
  if(record.publications!==undefined){const ids=new Set();for(const item of list(record.publications,'publications')){entry(item,'publications');if(!object(item)||item.ownerConfirmed!==true)throw new Error('Every CV publication requires explicit Owner confirmation of authorship.');if(item.referenceId){if(!/^reference:[^\s<>\\?#:]+$/.test(item.referenceId))throw new Error('Use a reference stable ID.');if(ids.has(item.referenceId))throw new Error('Duplicate CV publication reference.');ids.add(item.referenceId);}else text(item.title,'Publication title',{required:true});}}
  if(record.sections!==undefined){const ids=new Set();for(const section of list(record.sections,'sections')){if(!object(section)||!CV_SECTION_IDS.includes(section.id)||ids.has(section.id))throw new Error('Choose a unique supported CV section.');ids.add(section.id);if(section.visible!==undefined&&typeof section.visible!=='boolean')throw new Error('Section visibility must be a boolean.');if(section.order!==undefined&&(!Number.isInteger(section.order)||section.order<0))throw new Error('Section order must be a nonnegative integer.');}}
  return record;
}
export function normalizeCV(record={}) {validateCV(record);return {schemaVersion:1,...structuredClone(record),profile:{...(record.profile||{})},selectedResearch:structuredClone(record.selectedResearch||[]),selectedProjects:structuredClone(record.selectedProjects||[]),publications:structuredClone(record.publications||[])};}
function isPublic(node) {const data=node?.metadata||node||{};return node&&((node.visibility||data.visibility||'public')==='public')&&data.draft!==true&&!['draft','private','unlisted','archived'].includes(String(data.publicationStatus||node.publicationStatus||'').toLowerCase())&&data.demo!==true;}
function asEntry(value) {return typeof value==='string'?{title:value}:{...value};}
export function deriveCV(profile={},record={},nodes=[]) {
  const overrides=normalizeCV(record),resolvedProfile=Object.fromEntries(profileKeys.map(key=>[key,overrides.profile[key]??profile[key]??'']));
  const data={schemaVersion:1,profile:resolvedProfile};
  for(const key of [...textArrays,...entryArrays])data[key]=structuredClone(record[key]??profile[key==='awards'?'honors':key]??[]);
  if(!record.links){data.links=[...(data.links||[])];if(resolvedProfile.github&&!data.links.some(item=>item.url===resolvedProfile.github))data.links.push({title:'GitHub',url:resolvedProfile.github});}
  const index=new Map(nodes.map(node=>[node.id,node]));
  for(const key of ['selectedResearch','selectedProjects'])data[key]=overrides[key].flatMap(selection=>{const node=index.get(selection.id);return isPublic(node)?[{id:node.id,title:node.title||node.metadata?.title||node.id,description:selection.description??node.description??node.metadata?.description??'',url:node.path||node.url||'',tags:node.tags||[]}]:[];});
  data.publications=overrides.publications.flatMap(item=>{if(!item.referenceId)return [asEntry(item)];const node=index.get(item.referenceId);if(!isPublic(node))return [];const reference=node.metadata||node;return [{...reference,...item,title:reference.title||node.title,url:reference.url||node.path||'',authors:reference.authors||[],year:reference.year||''}];});
  // Legacy profile publications are already owner-authored, and are never inferred from references.
  if(record.publications===undefined)data.publications=[...(profile.publications||[])].map(asEntry);
  data.sections=CV_SECTION_IDS.map((id,order)=>({id,order,visible:true,...overrides.sections?.find(section=>section.id===id)})).sort((a,b)=>a.order-b.order||CV_SECTION_IDS.indexOf(a.id)-CV_SECTION_IDS.indexOf(b.id));
  data.visibleSections=data.sections.filter(section=>section.visible&&(section.id==='profile'?Boolean(resolvedProfile.bio):Array.isArray(data[section.id])&&data[section.id].length>0)).map(section=>({...section,title:CV_SECTION_TITLES[section.id]}));
  return data;
}
